BEGIN
CREATE ROLE ${DB_USER} WITH
    NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS 
    PASSWORD '${DB_PW}' VALID UNTIL 'infinity'
ALTER ROLE ${DB_USER}
    SET log_statement TO 'all'
COMMIT