version: 0.2

env:
  variables:
    IMAGE_BASE_NAME: "swisstopo/service-stac"
    SHELL: /bin/bash
    AWS_DEFAULT_REGION: eu-central-1
    USER: "aws_code_build"
    ENV: "dev"
    PIPENV_NOSPIN: 1
  parameter-store:
    CI_DOCKERHUB_USER: "/dockerhub/user"
    CI_DOCKERHUB_PASSWORD: "/dockerhub/password"

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo "Installing necessary dependencies"
      - docker login -u ${CI_DOCKERHUB_USER} -p ${CI_DOCKERHUB_PASSWORD}
      - apt-get update && apt-get install -y docker-compose python3-pip python3-venv gdal-bin
  pre_build:
    commands:
      - echo "export of the image tag for build and push purposes"
      # Reading git branch (the utility in the deploy script is unable to read it automatically
      # on CodeBuild)
      # see https://stackoverflow.com/questions/47657423/get-github-git-branch-for-aws-codebuild
      - export GITHUB_BRANCH="$(git symbolic-ref HEAD --short 2>/dev/null)"
      - |-
        if [ "${GITHUB_BRANCH}" = "" ] ; then
          GITHUB_BRANCH="$(git branch -a --contains HEAD | sed -n 2p | awk '{ printf $1 }')";
          export GITHUB_BRANCH=${GITHUB_BRANCH#remotes/origin/};
        fi
      - export COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - export GIT_TAG="$(git describe --tags || echo 'no version info')"
      - echo "GITHUB_BRANCH=${GITHUB_BRANCH} COMMIT_HASH=${COMMIT_HASH} GIT_TAG=${GIT_TAG}"
      - echo "creating a clean environment"
      - make ci
      - echo "linting code"
      - make lint

  build:
    commands:
      - |-
        if [ "${GIT_TAG}" = "undefined" ] ; then
          DOCKER_IMG_TAG="${IMAGE_BASE_NAME}:${GITHUB_BRANCH}.${COMMIT_HASH}"
        else
          DOCKER_IMG_TAG="${IMAGE_BASE_NAME}:${GIT_TAG}"
        fi
      - export DOCKER_IMG_TAG=${DOCKER_IMG_TAG}
      - export DOCKER_IMG_TAG_DEV="${DOCKER_IMG_TAG}-dev"
      - export DOCKER_IMG_TAG_LATEST="${IMAGE_BASE_NAME}:${GITHUB_BRANCH}.latest"
      - export DOCKER_IMG_TAG_LATEST_DEV="${IMAGE_BASE_NAME}:${GITHUB_BRANCH}.latest-dev"
      # Starting dev build for testing
      - echo "starting debug build on $(date)"
      - echo "Building docker debug image with tags ${DOCKER_IMG_TAG} and ${DOCKER_IMG_TAG_LATEST_DEV}"
      - >
        docker build
        --build-arg GIT_HASH="${COMMIT_HASH}"
        --build-arg GIT_BRANCH="${GITHUB_BRANCH}"
        --build-arg AUTHOR="CI"
        --build-arg VERSION="${GIT_TAG}"
        -t "${DOCKER_IMG_TAG_DEV}" -t "${DOCKER_IMG_TAG_LATEST_DEV}" --target debug .
      # Running tests
      # Note: the app container will 'exit 0' once tests are completed, we need to
      # stop the db as well then
      - docker-compose up --abort-on-container-exit
      # Starting prod build
      - echo "starting production build on $(date)"
      - echo "Building docker production image with tags ${DOCKER_IMG_TAG} and ${DOCKER_IMG_TAG_LATEST}"
      - >
        docker build
        --build-arg GIT_HASH="${COMMIT_HASH}"
        --build-arg GIT_BRANCH="${GITHUB_BRANCH}"
        --build-arg AUTHOR="CI"
        --build-arg VERSION="${GIT_TAG}"
        -t "${DOCKER_IMG_TAG}" -t "${DOCKER_IMG_TAG_LATEST}" --target production .

  post_build:
    commands:
      # Only push images built from develop and master to dockerhub
      - |
        if [ "${GITHUB_BRANCH}" = "master" ] || [ "${GITHUB_BRANCH}" = "develop" ]; then
          echo "Push production image ${DOCKER_IMG_TAG}"
          docker push ${DOCKER_IMG_TAG}
          echo "Push debug image ${DOCKER_IMG_TAG_DEV}"
          docker push ${DOCKER_IMG_TAG_DEV}
        fi
      # For develop aditionally push images with '*latest*' tags
      - |-
        if [ "${GITHUB_BRANCH}" = "develop" ]; then
          echo "Push production image ${DOCKER_IMG_TAG_LATEST}"
          docker push ${DOCKER_IMG_TAG_LATEST}
          echo "Push debug image ${DOCKER_IMG_TAG_LATEST_DEV}"
          docker push ${DOCKER_IMG_TAG_LATEST_DEV}
        fi
