openapi: 3.0.3
components:
  parameters:
    uploadId:
      name: uploadId
      in: path
      description: Local identifier of an asset's upload.
      required: true
      schema:
        type: string
    presignedUrl:
      name: presignedUrl
      in: path
      description: >-
        Presigned url returned by [Create a new Asset's multipart upload](#operation/createAssetUpload).

        Note: the url returned by the above endpoint is the full url including
        scheme, host and path
      required: true
      schema:
        type: string
    IfMatchWrite:
      name: If-Match
      in: header
      schema:
        type: string
      description: >-
        The RFC7232 `If-Match` header field makes the PUT/PATCH/DEL request method conditional. It is
        composed of a comma separated list of ETags or value "*".


        The server compares the client's ETags (sent with `If-Match`) with the ETag for its
        current version of the resource, and if both values don't match (that is, the resource has changed),
        the server sends back a `412 Precondition Failed` status, without a body, which tells the client that
        he would overwrite another changes of the resource.
      example: "d01af8b8ebbf899e30095be8754b377ddb0f0ed0f7fddbc33ac23b0d1969736b"
    IdempotencyKey:
      name: Idempotency-Key
      in: header
      schema:
        type: string
      description: >-
        A unique ID for the operation.
        This allows making the operation idempotent, so more fault tolerant.
        See IETF draft [draft-ietf-httpapi-idempotency-key-header](https://datatracker.ietf.org/doc/draft-ietf-httpapi-idempotency-key-header/).
      example: "8e03978e-40d5-43e8-bc93-6894a57f9324"
