version: 1
disable_existing_loggers: False # this allow to get logger at module level

root:
  handlers:
    - file-standard
    - file-json
    - console
  level: INFO
  propagate: True

loggers:
  stac_api.management:
    level: DEBUG
    handlers:
      - console-management
  stac_api:
    level: INFO
  middleware:
    level: INFO
  django:
    level: INFO
  django.db:
    level: DEBUG
  django.utils.autoreload:
    level: INFO
  gunicorn.error:
    handlers:
      - console
  gunicorn.access:
    handlers:
      - console

filters:
  isotime:
    (): logging_utilities.filters.TimeAttribute
    isotime: False
    utc_isotime: True
  django:
    (): logging_utilities.filters.django_request.JsonDjangoRequest
    include_keys:
      - request.path
      - request.method
      - request.headers
    exclude_keys:
      - request.headers.Authorization
      - request.headers.Proxy-Authorization
      - request.headers.Cookie

formatters:
  standard:
    (): logging_utilities.formatters.extra_formatter.ExtraFormatter
    format: "[%(utc_isotime)s] %(levelname)-8s - %(name)-26s : %(message)s"
    extra_fmt: " - collection: %(collection)s - item: %(item)s - asset: %(asset)s - duration: %(duration)s"
    # extra_pretty_print: True
  json:
    (): logging_utilities.formatters.json_formatter.JsonFormatter
    add_always_extra: True
    filter_attributes:
      - utc_isotime
    remove_empty: True
    fmt:
      time: utc_isotime
      level: levelname
      logger: name
      module: module
      function: funcName
      process: process
      thread: thread
      exc_info: exc_info
      message: message

handlers:
  console-management:
    level: WARNING
    class: logging.StreamHandler
    formatter: standard
    stream: ext://sys.stdout
    filters:
      - isotime
      - django
  console:
    level: ERROR
    class: logging.StreamHandler
    formatter: standard
    stream: ext://sys.stdout
    filters:
      - isotime
      - django
  file-standard:
    class: logging.FileHandler
    formatter: standard
    filename: ${BASE_DIR}/logs/management-standard-logs.txt
    mode: w
    filters:
      - isotime
      - django
  file-json:
    class: logging.FileHandler
    formatter: json
    filename: ${BASE_DIR}/logs/management-json-logs.json
    mode: w
    filters:
      - isotime
      - django
