openapi: 3.0.3
tags:
  - name: Capabilities
  - name: Data
  - name: STAC
  - name: Data Management
    description: |
      The endpoints in this section create, update or delete STAC metadata.

      See the [Tech Docs](https://docs.geo.admin.ch/download-data/stac-api/overview.html) for more details
      on authentication and supported media types.

  - name: Asset Upload Management
    description: |
      The endpoints in this section manage the process of uploading assets to the STAC catalog.

      See the [Tech Docs](https://docs.geo.admin.ch/download-data/stac-api/overview.html) for examples and
      more details on authentication and compression.

  - name: Collection Asset Upload Management
    description: |
      The endpoints in this section manage the process of uploading collection assets to the STAC catalog.
      The flow of the requests is the same as for assets that belong to features.

      See the [Tech Docs](https://docs.geo.admin.ch/download-data/stac-api/overview.html) for examples and
      more details on authentication and compression.
