# pylint: disable=C0301
# Generated by Django 3.1 on 2020-10-15 13:18

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='coverage',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                default=
                'MULTIPOLYGON(((2317000 913000 0,3057000 913000 0,3057000 1413000 0,2317000 1413000 0,2317000 913000 0)))',
                dim=3,
                srid=4326
            ),
        ),
    ]
