# Generated by Django 3.1 on 2020-10-16 14:23

import django.contrib.postgres.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='crs',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.URLField(default='http://www.opengis.net/def/crs/OGC/1.3/CRS84'),
                size=None
            ),
        ),
    ]
