# Generated by Django 3.1.2 on 2020-10-28 14:26

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    replaces = [('stac_api', '0004_auto_20201028_0759'), ('stac_api', '0005_auto_20201028_0837'),
                ('stac_api', '0006_auto_20201028_1143'), ('stac_api', '0007_auto_20201028_1148')]

    dependencies = [
        ('stac_api', '0003_auto_20201022_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionLink',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    )
                ),
                ('href', models.URLField()),
                ('rel', models.CharField(max_length=30)),
                ('link_type', models.CharField(blank=True, max_length=150)),
                ('title', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemLink',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    )
                ),
                ('href', models.URLField()),
                ('rel', models.CharField(max_length=30)),
                ('link_type', models.CharField(blank=True, max_length=150)),
                ('title', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='asset_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='stac_extension',
            new_name='stac_extensions',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='links',
        ),
        migrations.RemoveField(
            model_name='item',
            name='assets',
        ),
        migrations.RemoveField(
            model_name='item',
            name='links',
        ),
        migrations.RemoveField(
            model_name='item',
            name='location',
        ),
        migrations.DeleteModel(name='Link',),
        migrations.AddField(
            model_name='collectionlink',
            name='collection',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='links',
                related_query_name='link',
                to='stac_api.collection'
            ),
        ),
        migrations.AddField(
            model_name='itemlink',
            name='item',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='links',
                related_query_name='link',
                to='stac_api.item'
            ),
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='copy_from_href',
            new_name='href',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='proj',
            new_name='proj_epsq',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='location',
        ),
        migrations.AlterField(
            model_name='asset',
            name='geoadmin_variant',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='asset',
            name='feature',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='assets',
                related_query_name='asset',
                to='stac_api.item'
            ),
        ),
    ]
