# Generated by Django 3.1.7 on 2021-04-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0003_auto_20210325_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='checksum_multihash',
            field=models.CharField(blank=True, default=None, editable=False, max_length=255, null=True),
        ),
    ]
