# Generated by Django 3.1.2 on 2020-10-29 11:04

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0004_auto_20201028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='geoadmin_variant',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='summaries_eo_gsd',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='summaries_proj',
        ),
        migrations.AddField(
            model_name='collection',
            name='summaries',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='collection',
            name='extent',
        ),
        migrations.AddField(
            model_name='collection',
            name='extent',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
