# Generated by Django 3.1 on 2020-10-22 10:07 # pylint: disable=C0321

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0002_auto_20201016_1423'),
        ('stac_api', '0004_auto_20201015_1404'),
    ]

    operations = []
