# Generated by Django 3.1.7 on 2021-04-08 08:21

import django.core.serializers.json
import django.core.validators
import django.db.models.deletion
from django.db import migrations
from django.db import models

import stac_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0004_auto_20210408_0659'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetUpload',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('upload_id', models.CharField(max_length=255)),
                (
                    'status',
                    models.CharField(
                        choices=[(None, ''), ('in-progress', 'In Progress'),
                                 ('completed', 'Completed'), ('aborted', 'Aborted')],
                        default='in-progress',
                        max_length=32
                    )
                ),
                (
                    'number_parts',
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100)
                        ]
                    )
                ),
                (
                    'urls',
                    models.JSONField(
                        blank=True,
                        default=list,
                        encoder=django.core.serializers.json.DjangoJSONEncoder
                    )
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ended', models.DateTimeField(blank=True, default=None, null=True)),
                ('checksum_multihash', models.CharField(max_length=255)),
                ('etag', models.CharField(default=stac_api.models.compute_etag, max_length=56)),
                (
                    'asset',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='+',
                        to='stac_api.asset'
                    )
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name='assetupload',
            constraint=models.UniqueConstraint(
                fields=('asset', 'upload_id'), name='unique_together'
            ),
        ),
        migrations.AddConstraint(
            model_name='assetupload',
            constraint=models.UniqueConstraint(
                condition=models.Q(status='in-progress'),
                fields=('asset', 'status'),
                name='unique_in_progress'
            ),
        ),
    ]
