# Generated by Django 3.1 on 2020-10-22 11:31 # pylint: disable=C0301

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0005_merge_20201022_1007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='northeast',
            new_name='extent',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='coverage',
            new_name='geometry',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='southwest',
        ),
        migrations.RemoveField(
            model_name='item',
            name='GeoJSON_type',
        ),
        migrations.RemoveField(
            model_name='item',
            name='geometry_coordinates',
        ),
        migrations.RemoveField(
            model_name='item',
            name='geometry_type',
        ),
        migrations.RemoveField(
            model_name='item',
            name='northeast',
        ),
        migrations.RemoveField(
            model_name='item',
            name='southwest',
        ),
    ]
