# Generated by Django 3.1.7 on 2021-04-19 14:09

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0005_auto_20210408_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='collection',
            field=models.ForeignKey(
                help_text=
                '\n    <div class=SearchUsage>\n        Search Usage:\n        <ul>\n            <li>\n                <i>arg</i> will make a non exact search checking if <i>arg</i> is part of\n                the collection ID\n            </li>\n            <li>\n                Multiple <i>arg</i> can be used, separated by spaces. This will search for all\n                collections ID containing all arguments.\n            </li>\n            <li>\n                <i>"collectionID"</i> will make an exact search for the specified collection.\n            </li>\n        </ul>\n        Examples :\n        <ul>\n            <li>\n                Searching for <i>pixelkarte</i> will return all collections which have\n                pixelkarte as a part of their collection ID\n            </li>\n            <li>\n                Searching for <i>pixelkarte 2016 4</i> will return all collection\n                which have pixelkarte, 2016 AND 4 as part of their collection ID\n            </li>\n            <li>\n                Searching for <i>ch.swisstopo.pixelkarte.example</i> will yield only this\n                collection, if this collection exists. Please note that it would not return\n                a collection named ch.swisstopo.pixelkarte.example.2.\n            </li>\n        </ul>\n    </div>',
                on_delete=django.db.models.deletion.PROTECT,
                to='stac_api.collection'
            ),
        ),
    ]
