# Generated by Django 3.1.2 on 2020-11-02 10:09

import django.core.serializers.json
from django.db import migrations
from django.db import models

import stac_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0007_auto_20201030_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='extent',
            field=models.JSONField(
                default=stac_api.models.get_default_extent_value,
                editable=False,
                encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
        migrations.AlterField(
            model_name='collection',
            name='summaries',
            field=models.JSONField(
                default=stac_api.models.get_default_summaries_value,
                editable=False,
                encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
    ]
