# Generated by Django 3.1.10 on 2021-06-21 08:40

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0007_auto_20210421_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
