# Generated by Django 3.1.10 on 2021-06-21 13:57

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0008_auto_20210621_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='published',
            field=models.BooleanField(
                default=True,
                help_text=
                "When not published the collection doesn't appear on the api/stac/v0.9/collections "
                "endpoint and its items are not listed in /search endpoint."
                "<p><i>NOTE: unpublished collections/items can still be accessed by their path.</ip></p>"
            ),
        ),
    ]
