# Generated by Django 3.1.2 on 2020-11-02 14:06

import django.contrib.postgres.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0008_auto_20201102_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='properties_eo_gsd',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(), blank=True, editable=False, null=True, size=None
            ),
        ),
    ]
