# Generated by Django 3.1.10 on 2021-06-21 14:53

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0009_collection_published'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['published'], name='collection_published_idx'),
        ),
    ]
