# Generated by Django 3.1.2 on 2020-11-04 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0009_auto_20201102_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='stac_extension',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='stac_version',
        ),
        migrations.RemoveField(
            model_name='item',
            name='stac_extensions',
        ),
        migrations.RemoveField(
            model_name='item',
            name='stac_version',
        ),
    ]
