# Generated by Django 3.1.10 on 2021-06-23 05:21

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0010_auto_20210621_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='properties_datetime',
            field=models.DateTimeField(
                blank=True,
                help_text=
                'Enter date in <i>yyyy-mm-dd</i> format, and time in UTC <i>hh:mm:ss</i> format',
                null=True
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='properties_end_datetime',
            field=models.DateTimeField(
                blank=True,
                help_text=
                'Enter date in <i>yyyy-mm-dd</i> format, and time in UTC <i>hh:mm:ss</i> format',
                null=True
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='properties_start_datetime',
            field=models.DateTimeField(
                blank=True,
                help_text=
                'Enter date in <i>yyyy-mm-dd</i> format, and time in UTC <i>hh:mm:ss</i> format',
                null=True
            ),
        ),
    ]
