# Generated by Django 3.1.10 on 2021-07-09 07:34

from django.db import migrations
from django.db import models

import stac_api.validators


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0011_auto_20210623_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='eo_gsd',
            field=models.FloatField(
                blank=True, null=True, validators=[stac_api.validators.validate_eo_gsd]
            ),
        ),
    ]
