# Generated by Django 3.1.13 on 2021-07-15 13:58

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.core.serializers.json
from django.db import migrations
from django.db import models

import stac_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0013_crypto_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='summaries_eo_gsd',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(), blank=True, default=list, editable=False, size=None
            ),
        ),
        migrations.AddField(
            model_name='collection',
            name='summaries_geoadmin_variant',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=25),
                blank=True,
                default=list,
                editable=False,
                size=None
            ),
        ),
        migrations.AddField(
            model_name='collection',
            name='summaries_proj_epsg',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                blank=True,
                default=list,
                editable=False,
                size=None
            ),
        ),
        migrations.AlterField(
            model_name='asset',
            name='etag',
            field=models.CharField(
                default=stac_api.models.compute_etag, editable=False, max_length=56
            ),
        ),
        migrations.AlterField(
            model_name='asset',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='etag',
            field=models.CharField(
                default=stac_api.models.compute_etag, editable=False, max_length=56
            ),
        ),
        migrations.AlterField(
            model_name='collection',
            name='extent_geometry',
            field=django.contrib.gis.db.models.fields.PolygonField(
                blank=True, default=None, editable=False, null=True, srid=4326
            ),
        ),
        migrations.AlterField(
            model_name='collection',
            name='summaries',
            field=models.JSONField(
                default=dict,
                editable=False,
                encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
        migrations.AlterField(
            model_name='collection',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='etag',
            field=models.CharField(
                default=stac_api.models.compute_etag, editable=False, max_length=56
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
