# Generated by Django 3.1.13 on 2021-08-18 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0014_auto_20210715_1358'),
    ]

    operations = [
        migrations.RunSQL(
            '''
            WITH collection_summaries AS (
                SELECT
                    item.collection_id AS collection_id,
                    array_remove(array_agg(DISTINCT(asset.proj_epsg)), null) AS proj_epsg,
                    array_remove(array_agg(DISTINCT(asset.geoadmin_variant)), null) AS geoadmin_variant,
                    array_remove(array_agg(DISTINCT(asset.eo_gsd)), null) AS eo_gsd
                FROM stac_api_item AS item
                LEFT JOIN stac_api_asset AS asset ON (asset.item_id = item.id)
                GROUP BY item.collection_id
            )
            UPDATE stac_api_collection
            SET
                summaries_proj_epsg        = collection_summaries.proj_epsg,
                summaries_geoadmin_variant = collection_summaries.geoadmin_variant,
                summaries_eo_gsd           = collection_summaries.eo_gsd
            FROM collection_summaries
            WHERE collection_summaries.collection_id = stac_api_collection.id;
            ''',
            reverse_sql=migrations.RunSQL.noop
        )
    ]
