# Generated by Django 3.1.2 on 2020-11-04 22:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0014_remove_item_geometry_old'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='feature',
            new_name='item',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='item_type',
        ),
        migrations.AddField(
            model_name='asset',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='item',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='eo_gsd',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='geoadmin_lang',
            field=models.CharField(choices=[('de', 'German'), ('it', 'Italian'), ('fr', 'French'), ('rm', 'Romansh'), ('en', 'English'), ('', '')], default='', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='geoadmin_variant',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='collectionlink',
            name='rel',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='itemlink',
            name='rel',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
