# Generated by Django 3.1.2 on 2020-11-05 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0015_auto_20201104_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionlink',
            name='link_type',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='collectionlink',
            name='rel',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='collectionlink',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='itemlink',
            name='link_type',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='itemlink',
            name='rel',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='itemlink',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='collectionlink',
            unique_together={('rel', 'collection')},
        ),
    ]
