# Generated by Django 3.1.2 on 2020-11-06 07:12

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0016_auto_20201105_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='extent_geometry',
            field=django.contrib.gis.db.models.fields.PolygonField(
                default=None, editable=False, null=True, srid=4326
            ),
        ),
    ]
