# Generated by Django 3.1.2 on 2020-11-05 15:06

import django.contrib.postgres.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0016_auto_20201105_0538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='extent',
        ),
        migrations.AddField(
            model_name='collection',
            name='bbox',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.FloatField(blank=True, null=True),
                    blank=True,
                    null=True,
                    size=None
                ),
                blank=True,
                editable=False,
                null=True,
                size=None
            ),
        ),
        migrations.AddField(
            model_name='collection',
            name='end_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='start_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
