# Generated by Django 3.1.13 on 2021-09-02 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0016_auto_20210902_1731'),
    ]

    operations = [
        migrations.RunSQL(
            '''
            WITH collection_summaries AS (
                SELECT
                    item.collection_id AS collection_id,
                    array_remove(array_agg(DISTINCT(asset.geoadmin_lang)), null) AS geoadmin_lang
                FROM stac_api_item AS item
                LEFT JOIN stac_api_asset AS asset ON (asset.item_id = item.id)
                GROUP BY item.collection_id
            )
            UPDATE stac_api_collection
            SET
                summaries_geoadmin_lang = collection_summaries.geoadmin_lang
            FROM collection_summaries
            WHERE collection_summaries.collection_id = stac_api_collection.id;
            ''',
            reverse_sql=migrations.RunSQL.noop
        )
    ]
