# Generated by Django 3.1.2 on 2020-11-09 06:30

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0017_collection_extent_geometry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='extent',
        ),
        migrations.AddField(
            model_name='collection',
            name='bbox',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.FloatField(blank=True, null=True),
                    blank=True,
                    null=True,
                    size=None
                ),
                blank=True,
                editable=False,
                null=True,
                size=None
            ),
        ),
        migrations.AddField(
            model_name='collection',
            name='cache_end_datetime',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='cache_start_datetime',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='extent_geometry',
            field=django.contrib.gis.db.models.fields.PolygonField(
                default=None, null=True, srid=4326
            ),
        ),
    ]
