# Generated by Django 3.1.13 on 2021-09-15 14:05

import django.core.serializers.json
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0017_data_collection_summaries_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetupload',
            name='md5_parts',
            field=models.JSONField(
                blank=True,
                default=list,
                editable=False,
                encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
    ]
