# Generated by Django 3.1.2 on 2020-11-06 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0017_auto_20201105_1506'),
        ('stac_api', '0017_collection_extent_geometry'),
    ]

    operations = []
