# Generated by Django 3.1.2 on 2020-11-06 09:54

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0018_merge_20201106_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='extent_geometry',
            field=django.contrib.gis.db.models.fields.PolygonField(
                default=None, null=True, srid=4326
            ),
        ),
    ]
