# Generated by Django 3.1.3 on 2020-11-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0018_auto_20201109_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='properties_end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='properties_start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='properties_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
