# Generated by Django 3.1.2 on 2020-11-06 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0019_auto_20201106_0954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='end_date',
            new_name='cache_end_datetime',
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='start_date',
            new_name='cache_start_datetime',
        ),
    ]
