# Generated by Django 3.1.3 on 2020-11-11 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0021_auto_20201109_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='keywords',
        ),
        migrations.DeleteModel(name='Keyword',),
    ]
