# Generated by Django 3.1.3 on 2020-11-12 08:35

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0022_auto_20201111_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='properties_eo_gsd',
        ),
        migrations.AddField(
            model_name='item',
            name='properties_eo_gsd',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
