# Generated by Django 4.0.10 on 2023-03-22 06:16

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0025_add_asset_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetupload',
            name='content_encoding',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
