# Generated by Django 3.1.3 on 2020-11-16 10:44

import django.contrib.gis.db.models.fields
from django.db import migrations

import stac_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0026_data_remove_ro_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='extent_geometry',
            field=django.contrib.gis.db.models.fields.PolygonField(
                blank=True,
                default=None,
                editable=False,
                null=True,
                srid=4326,
                validators=[stac_api.models.validate_geometry]
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PolygonField(
                default=
                'SRID=4326;POLYGON ((5.96 45.82, 5.96 47.81, 10.49 47.81, 10.49 45.82, 5.96 45.82))',
                srid=4326,
                validators=[stac_api.models.validate_geometry]
            ),
        ),
    ]
