# Generated by Django 3.1.2 on 2020-11-16 10:32

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0027_auto_20201116_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='providers',
        ),
        migrations.AddField(
            model_name='provider',
            name='collection',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='providers', related_query_name='provider', to='stac_api.collection'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='provider',
            name='roles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=9), help_text="Comma-separated list of roles. Possible values are 'licensor', 'producer', 'processor', 'host'", size=None),
        ),
        migrations.AlterUniqueTogether(
            name='provider',
            unique_together={('collection', 'name')},
        ),
    ]
