# Generated by Django 4.0.10 on 2024-03-19 14:58

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0028_alter_asset_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionlink',
            name='href',
            field=models.URLField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='itemlink',
            name='href',
            field=models.URLField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='landingpagelink',
            name='href',
            field=models.URLField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='provider',
            name='url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
