# Generated by Django 3.1.3 on 2020-11-18 19:39

import django.contrib.postgres.fields
from django.db import migrations
from django.db import models

import stac_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0028_auto_20201116_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='collection',
        ),
        migrations.AlterField(
            model_name='asset',
            name='geoadmin_variant',
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                validators=[stac_api.models.validate_geoadmin_variant]
            ),
        ),
    ]
