# Generated by Django 3.1.3 on 2020-11-18 19:31

import django.contrib.postgres.fields
from django.db import migrations
from django.db import models

import stac_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0029_auto_20201118_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_name',
            field=models.CharField(
                max_length=255, unique=True, validators=[stac_api.models.validate_name]
            ),
        ),
        migrations.AlterField(
            model_name='collection',
            name='collection_name',
            field=models.CharField(
                max_length=255, unique=True, validators=[stac_api.models.validate_name]
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(
                max_length=255, unique=True, validators=[stac_api.models.validate_name]
            ),
        ),
        migrations.AlterField(
            model_name='provider',
            name='roles',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=9),
                help_text=
                'Comma-separated list of roles. Possible values are licensor, producer, processor, host',
                size=None
            ),
        ),
    ]
