# Generated by Django 3.1.3 on 2020-11-19 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0030_auto_20201118_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='asset_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='collection_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_name',
            new_name='name',
        ),
    ]
