# Generated by Django 5.0.6 on 2024-07-04 11:46

import django.contrib.postgres.fields
from django.db import migrations
from django.db import models

import stac_api.models.general
import stac_api.validators


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0031_alter_collection_extent_geometry_alter_item_geometry'),
    ]

    operations = [
        migrations.DeleteModel(name='ConformancePage',),
        migrations.AddField(
            model_name='landingpage',
            name='conformsTo',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.URLField(),
                default=stac_api.models.general.get_conformance_default_links,
                help_text='Comma-separated list of URLs for the value conformsTo',
                size=None
            ),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='version',
            field=models.CharField(default='v1', max_length=255),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='name',
            field=models.CharField(
                default='ch',
                max_length=255,
                validators=[stac_api.validators.validate_name],
                verbose_name='id'
            ),
        ),
    ]
