# Generated by Django 3.1.3 on 2020-11-23 11:57

from django.db import migrations
from django.db import models

import stac_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0031_auto_20201119_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(
                max_length=255,
                unique=True,
                validators=[stac_api.models.validate_name],
                verbose_name='id'
            ),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(
                max_length=255,
                unique=True,
                validators=[stac_api.models.validate_name],
                verbose_name='id'
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(
                max_length=255,
                unique=True,
                validators=[stac_api.models.validate_name],
                verbose_name='id'
            ),
        ),
    ]
