# Generated by Django 3.1.3 on 2020-11-23 10:54

import django.db.models.deletion
from django.db import migrations
from django.db import models

import stac_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0031_auto_20201119_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    )
                ),
                (
                    'name',
                    models.CharField(
                        default='ch',
                        max_length=255,
                        unique=True,
                        validators=[stac_api.models.validate_name],
                        verbose_name='id'
                    )
                ),
                ('title', models.CharField(default='data.geo.admin.ch', max_length=255)),
                (
                    'description',
                    models.TextField(
                        default='Data Catalog of the Swiss Federal Spatial Data Infrastructure'
                    )
                ),
            ],
            options={
                'verbose_name': 'STAC Landing Page',
            },
        ),
        migrations.CreateModel(
            name='LandingPageLink',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    )
                ),
                ('href', models.URLField()),
                (
                    'rel',
                    models.CharField(max_length=30, validators=[stac_api.models.validate_link_rel])
                ),
                ('link_type', models.CharField(blank=True, max_length=150, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                (
                    'landing_page',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='links',
                        related_query_name='link',
                        to='stac_api.landingpage'
                    )
                ),
            ],
            options={
                'unique_together': {('rel', 'landing_page')},
            },
        ),
    ]
