# Generated by Django 5.0.6 on 2024-07-04 11:57

from django.db import migrations


def add_landing_page_version(apps, schema_editor):
    # Truncate the landing page table and add the versions v0.9 and v1
    LandingPage = apps.get_model("stac_api", "LandingPage")
    LandingPage.objects.all().delete()
    lp = LandingPage()
    lp.name = 'ch'
    lp.title = 'data.geo.admin.ch'
    lp.description = 'Data Catalog of the Swiss Federal Spatial Data Infrastructure'
    lp.version = 'v0.9'
    lp.conformsTo = [
        'http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/core',
        'http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/oas30',
        'http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/geojson'
    ]
    lp.save()
    lp = LandingPage()
    lp.name = 'ch'
    lp.title = 'data.geo.admin.ch'
    lp.description = 'Data Catalog of the Swiss Federal Spatial Data Infrastructure'
    lp.version = 'v1'
    lp.conformsTo = [
        'https://api.stacspec.org/v1.0.0/core',
        'https://api.stacspec.org/v1.0.0/collections',
        'http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/core',
        'http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/oas30',
        'http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/geojson'
    ]
    lp.save()


def reverse_landing_page_version(apps, schema_editor):
    # Remove the landing page v0.9
    LandingPage = apps.get_model("stac_api", "LandingPage")
    lp = LandingPage.objects.get(version='v0.9')
    lp.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0032_delete_conformancepage_landingpage_conformsto_and_more'),
    ]

    operations = [
        migrations.RunPython(add_landing_page_version, reverse_landing_page_version),
    ]
