# Generated by Django 3.1.3 on 2020-11-25 18:42

import django.contrib.postgres.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0033_landingpage_landingpagelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='roles',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=9),
                blank=True,
                help_text=
                'Comma-separated list of roles. Possible values are licensor, producer, processor, host',
                null=True,
                size=None
            ),
        ),
        migrations.AlterField(
            model_name='provider',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
