# Generated by Django 5.0.6 on 2024-07-09 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0032_alter_asset_file'),
        ('stac_api', '0033_auto_20240704_1157'),
    ]

    operations = []
