# Generated by Django 3.1.3 on 2020-11-24 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0033_landingpage_landingpagelink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='properties_eo_gsd',
        ),
    ]
