# Generated by Django 5.0.6 on 2024-07-09 14:10

import django.contrib.postgres.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0034_merge_0032_alter_asset_file_0033_auto_20240704_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='roles',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=None,
                help_text='Comma-separated list of roles to describe the purpose of the asset',
                null=True,
                size=None
            ),
        ),
    ]
