# Generated by Django 3.1.3 on 2020-11-26 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0034_auto_20201125_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='properties_eo_gsd',
        ),
    ]
