# Generated by Django 3.1.3 on 2020-12-08 12:24

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0036_auto_20201202_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
