# Generated by Django 5.0.7 on 2024-07-16 15:31

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0036_collectionasset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_external',
            field=models.BooleanField(
                default=False, help_text='Whether this asset is hosted externally'
            ),
        ),
        migrations.AddField(
            model_name='collectionasset',
            name='is_external',
            field=models.BooleanField(
                default=False, help_text='Whether this asset is hosted externally'
            ),
        ),
    ]
