# Generated by Django 3.1.3 on 2020-12-03 09:52

import django.contrib.postgres.fields
from django.db import migrations
from django.db import models

import stac_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0036_auto_20201202_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConformancePage',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    )
                ),
                (
                    'conformsTo',
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.URLField(),
                        default=stac_api.models.get_conformance_default_links,
                        help_text='Comma-separated list of URLs for the value conformsTo',
                        size=None
                    )
                ),
            ],
            options={
                'verbose_name': 'STAC Conformance Page',
            },
        ),
    ]
