# Generated by Django 5.0.7 on 2024-07-18 09:09

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0037_asset_is_external_collectionasset_is_external'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='allow_external_assets',
            field=models.BooleanField(
                default=False,
                help_text='Whether this collection can have assets that are hosted externally'
            ),
        ),
    ]
