# Generated by Django 3.1.4 on 2020-12-09 22:11

from django.db import migrations
from django.db import models

import stac_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0040_auto_20201210_0805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='href',
        ),
        migrations.AddField(
            model_name='asset',
            name='file',
            field=models.FileField(
                blank=True, null=True, upload_to=stac_api.models.upload_asset_to_path_hook
            ),
        ),
    ]
