# Generated by Django 5.0.7 on 2024-07-19 13:16

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0040_collection_external_asset_pattern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='external_asset_pattern',
            field=models.CharField(
                blank=True,
                help_text='The regex pattern for allowed external URLs',
                max_length=1024
            ),
        ),
    ]
