# Generated by Django 5.0.7 on 2024-07-23 08:19

import django.contrib.postgres.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0042_remove_collectionasset_is_external'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='external_asset_pattern',
        ),
        migrations.AddField(
            model_name='collection',
            name='external_asset_whitelist',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                help_text=
                'Provide a comma separated list of protocol://domain values for the external asset url validation',
                size=None
            ),
        ),
    ]
