# Generated by Django 3.1.4 on 2020-12-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0043_auto_20201215_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='etag',
            field=models.CharField(default='d769621b-1e09-46db-9bdc-b99c481963e7', editable=False, max_length=56),
        ),
        migrations.AlterField(
            model_name='collection',
            name='etag',
            field=models.CharField(default='33b2809f-e9ef-4458-9921-8748d019323d', editable=False, max_length=56),
        ),
        migrations.AlterField(
            model_name='item',
            name='etag',
            field=models.CharField(default='0592cbf4-da72-4f33-9b32-70f4ba4c2938', editable=False, max_length=56),
        ),
    ]
