# Generated by Django 3.1.4 on 2020-12-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0044_auto_20201221_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='etag',
            field=models.CharField(editable=False, max_length=56),
        ),
        migrations.AlterField(
            model_name='collection',
            name='etag',
            field=models.CharField(editable=False, max_length=56),
        ),
        migrations.AlterField(
            model_name='item',
            name='etag',
            field=models.CharField(editable=False, max_length=56),
        ),
    ]
