# Generated by Django 3.1.4 on 2021-01-06 07:36

from django.db import migrations, models
import stac_api.validators


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0045_auto_20201223_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=255, validators=[stac_api.validators.validate_name], verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=255, validators=[stac_api.validators.validate_name], verbose_name='id'),
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('item', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('collection', 'name')},
        ),
    ]
