# Generated by Django 3.1.4 on 2020-12-24 12:03

from django.db import migrations
from django.db import models

import stac_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0046_data_default_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='checksum_multihash',
            field=models.CharField(blank=True, default='', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='asset',
            name='file',
            field=models.FileField(
                max_length=255, upload_to=stac_api.models.upload_asset_to_path_hook
            ),
        ),
    ]
