# Generated by Django 3.1.5 on 2021-01-13 09:47

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0048_auto_20201224_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='geoadmin_lang',
            field=models.CharField(
                blank=True,
                choices=[(None, ''), ('de', 'German'), ('it', 'Italian'), ('fr', 'French'),
                         ('rm', 'Romansh'), ('en', 'English')],
                default=None,
                max_length=2,
                null=True
            ),
        ),
    ]
