# Generated by Django 5.0.8 on 2024-08-14 11:13

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0048_remove_item_update_item_collection_extent_trigger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='properties_expires',
            field=models.DateTimeField(
                blank=True,
                help_text=
                'Enter date in <i>yyyy-mm-dd</i> format, and time in UTC <i>hh:mm:ss</i> format',
                null=True
            ),
        ),
    ]
