# Generated by Django 5.0.8 on 2024-10-09 11:45

from django.db import migrations


def add_landing_page_version(apps, schema_editor):
    LandingPage = apps.get_model("stac_api", "LandingPage")
    lp = LandingPage.objects.get(version='v1')
    lp.conformsTo.insert(2, 'https://api.stacspec.org/v1.0.0/ogcapi-features')
    lp.conformsTo.insert(2, 'https://api.stacspec.org/v1.0.0/item-search')
    lp.save()


class Migration(migrations.Migration):
    dependencies = [
        ("stac_api", "0050_collectionassetupload_and_more"),
    ]

    operations = [migrations.RunPython(add_landing_page_version)]
