# Generated by Django 5.0.8 on 2024-10-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stac_api", "0050_collectionassetupload_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="file_size",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="assetupload",
            name="file_size",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="collection",
            name="total_data_size",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="collectionasset",
            name="file_size",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="collectionassetupload",
            name="file_size",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="total_data_size",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
