# Generated by Django 5.0.8 on 2024-10-08 13:44

import pgtrigger.compiler
import pgtrigger.migrations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stac_api", "0051_asset_file_size_assetupload_file_size_and_more"),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name="asset",
            trigger=pgtrigger.compiler.Trigger(
                name="add_del_asset_item_file_size_trigger",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    declare="DECLARE asset_instance stac_api_asset%ROWTYPE; item_data_size RECORD;",
                    func=
                    "\n        asset_instance = COALESCE(NEW, OLD);\n\n        -- Compute item total_data_size (sum aggregation of asset's file_size)\n        SELECT\n           COALESCE(SUM(NULLIF(asset.file_size, 0)), 0) AS sum_file_size\n        INTO item_data_size\n        FROM stac_api_asset AS asset\n        WHERE asset.item_id = asset_instance.item_id;\n\n        -- Update related item file_size variables\n        UPDATE stac_api_item SET\n            total_data_size = item_data_size.sum_file_size\n        WHERE id = asset_instance.item_id;\n\n        RAISE INFO 'item.id=% total_data_size updated, due to asset.name=% updates.',\n            asset_instance.item_id, asset_instance.name;\n\n        RETURN asset_instance;\n        ",
                    hash="5826a4ed0933ce28310df084679783e8b50f7d3e",
                    operation="INSERT OR DELETE",
                    pgid="pgtrigger_add_del_asset_item_file_size_trigger_b2d65",
                    table="stac_api_asset",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="asset",
            trigger=pgtrigger.compiler.Trigger(
                name="update_asset_item_file_size_trigger",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.file_size IS DISTINCT FROM NEW.file_size)",
                    declare="DECLARE asset_instance stac_api_asset%ROWTYPE; item_data_size RECORD;",
                    func=
                    "\n        asset_instance = COALESCE(NEW, OLD);\n\n        -- Compute item total_data_size (sum aggregation of asset's file_size)\n        SELECT\n           COALESCE(SUM(NULLIF(asset.file_size, 0)), 0) AS sum_file_size\n        INTO item_data_size\n        FROM stac_api_asset AS asset\n        WHERE asset.item_id = asset_instance.item_id;\n\n        -- Update related item file_size variables\n        UPDATE stac_api_item SET\n            total_data_size = item_data_size.sum_file_size\n        WHERE id = asset_instance.item_id;\n\n        RAISE INFO 'item.id=% total_data_size updated, due to asset.name=% updates.',\n            asset_instance.item_id, asset_instance.name;\n\n        RETURN asset_instance;\n        ",
                    hash="1d5c08a45a5e8feed4bb9b42949bc81ec4759f7a",
                    operation="UPDATE",
                    pgid="pgtrigger_update_asset_item_file_size_trigger_316e8",
                    table="stac_api_asset",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="collectionasset",
            trigger=pgtrigger.compiler.Trigger(
                name="add_del_col_asset_col_file_size_trigger",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    declare=
                    "DECLARE asset_instance stac_api_collectionasset%ROWTYPE; item_data_size RECORD; collectionasset_file_size RECORD;",
                    func=
                    "\n        asset_instance = COALESCE(NEW, OLD);\n\n        -- Compute collection total_data_size (sum aggregation of item's total_data_size)\n        SELECT\n            COALESCE(SUM(NULLIF(item.total_data_size, 0)), 0) AS sum_file_size\n        INTO item_data_size\n        FROM stac_api_item AS item\n        WHERE item.collection_id = asset_instance.collection_id;\n\n        SELECT\n            COALESCE(SUM(NULLIF(collectionasset.file_size, 0)), 0) AS sum_file_size\n        INTO collectionasset_file_size\n        FROM stac_api_collectionasset AS collectionasset\n        WHERE collectionasset.collection_id = asset_instance.collection_id;\n\n        -- Update related collection file_size variables\n        UPDATE stac_api_collection SET\n            total_data_size = item_data_size.sum_file_size + collectionasset_file_size.sum_file_size\n        WHERE id = asset_instance.collection_id;\n\n        RAISE INFO 'collection.id=% total_data_size updated, due to item.name=% updates.',\n            asset_instance.collection_id, asset_instance.name;\n\n        RETURN asset_instance;\n        ",
                    hash="f01f1687c06c67e76032b3b8076f9176745bdf45",
                    operation="INSERT OR DELETE",
                    pgid="pgtrigger_add_del_col_asset_col_file_size_trigger_fb765",
                    table="stac_api_collectionasset",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="collectionasset",
            trigger=pgtrigger.compiler.Trigger(
                name="update_col_asset_col_file_size_trigger",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    declare=
                    "DECLARE asset_instance stac_api_collectionasset%ROWTYPE; item_data_size RECORD; collectionasset_file_size RECORD;",
                    func=
                    "\n        asset_instance = COALESCE(NEW, OLD);\n\n        -- Compute collection total_data_size (sum aggregation of item's total_data_size)\n        SELECT\n            COALESCE(SUM(NULLIF(item.total_data_size, 0)), 0) AS sum_file_size\n        INTO item_data_size\n        FROM stac_api_item AS item\n        WHERE item.collection_id = asset_instance.collection_id;\n\n        SELECT\n            COALESCE(SUM(NULLIF(collectionasset.file_size, 0)), 0) AS sum_file_size\n        INTO collectionasset_file_size\n        FROM stac_api_collectionasset AS collectionasset\n        WHERE collectionasset.collection_id = asset_instance.collection_id;\n\n        -- Update related collection file_size variables\n        UPDATE stac_api_collection SET\n            total_data_size = item_data_size.sum_file_size + collectionasset_file_size.sum_file_size\n        WHERE id = asset_instance.collection_id;\n\n        RAISE INFO 'collection.id=% total_data_size updated, due to item.name=% updates.',\n            asset_instance.collection_id, asset_instance.name;\n\n        RETURN asset_instance;\n        ",
                    hash="c50165c22caffbede5ce6fb1d813ce0f2c68f4d0",
                    operation="UPDATE",
                    pgid="pgtrigger_update_col_asset_col_file_size_trigger_1d5be",
                    table="stac_api_collectionasset",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="item",
            trigger=pgtrigger.compiler.Trigger(
                name="add_del_item_collection_file_size_trigger",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    declare=
                    "DECLARE item_instance stac_api_item%ROWTYPE; item_data_size RECORD; collectionasset_file_size RECORD;",
                    func=
                    "\n        item_instance = COALESCE(NEW, OLD);\n\n        -- Compute collection total_data_size (sum aggregation of item's total_data_size)\n        SELECT\n            COALESCE(SUM(NULLIF(item.total_data_size, 0)), 0) AS sum_file_size\n        INTO item_data_size\n        FROM stac_api_item AS item\n        WHERE item.collection_id = item_instance.collection_id;\n\n        SELECT\n            COALESCE(SUM(NULLIF(collectionasset.file_size, 0)), 0) AS sum_file_size\n        INTO collectionasset_file_size\n        FROM stac_api_collectionasset AS collectionasset\n        WHERE collectionasset.collection_id = item_instance.collection_id;\n\n        -- Update related collection file_size variables\n        UPDATE stac_api_collection SET\n            total_data_size = item_data_size.sum_file_size + collectionasset_file_size.sum_file_size\n        WHERE id = item_instance.collection_id;\n\n        RAISE INFO 'collection.id=% total_data_size updated, due to item.name=% updates.',\n            item_instance.collection_id, item_instance.name;\n\n        RETURN item_instance;\n        ",
                    hash="b6169b0990b8292bc3e4e6c58f1f9b43a69e2227",
                    operation="INSERT OR DELETE",
                    pgid="pgtrigger_add_del_item_collection_file_size_trigger_e1f24",
                    table="stac_api_item",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="item",
            trigger=pgtrigger.compiler.Trigger(
                name="update_item_collection_file_size_trigger",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.total_data_size IS DISTINCT FROM NEW.total_data_size)",
                    declare=
                    "DECLARE item_instance stac_api_item%ROWTYPE; item_data_size RECORD; collectionasset_file_size RECORD;",
                    func=
                    "\n        item_instance = COALESCE(NEW, OLD);\n\n        -- Compute collection total_data_size (sum aggregation of item's total_data_size)\n        SELECT\n            COALESCE(SUM(NULLIF(item.total_data_size, 0)), 0) AS sum_file_size\n        INTO item_data_size\n        FROM stac_api_item AS item\n        WHERE item.collection_id = item_instance.collection_id;\n\n        SELECT\n            COALESCE(SUM(NULLIF(collectionasset.file_size, 0)), 0) AS sum_file_size\n        INTO collectionasset_file_size\n        FROM stac_api_collectionasset AS collectionasset\n        WHERE collectionasset.collection_id = item_instance.collection_id;\n\n        -- Update related collection file_size variables\n        UPDATE stac_api_collection SET\n            total_data_size = item_data_size.sum_file_size + collectionasset_file_size.sum_file_size\n        WHERE id = item_instance.collection_id;\n\n        RAISE INFO 'collection.id=% total_data_size updated, due to item.name=% updates.',\n            item_instance.collection_id, item_instance.name;\n\n        RETURN item_instance;\n        ",
                    hash="60276494d16ade5455df7015471a1bb24ec8fbe4",
                    operation="UPDATE",
                    pgid="pgtrigger_update_item_collection_file_size_trigger_83572",
                    table="stac_api_item",
                    when="AFTER",
                ),
            ),
        ),
    ]
