# Generated by Django 3.1.5 on 2021-01-28 09:49

from django.db import migrations
from django.db import models

import stac_api.validators


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0052_data_rename_asset_media_type_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='geoadmin_variant',
            field=models.CharField(
                blank=True,
                max_length=25,
                null=True,
                validators=[stac_api.validators.validate_geoadmin_variant]
            ),
        ),
    ]
