# Generated by Django 5.0.8 on 2024-11-06 16:09

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0053_alter_asset_media_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='forecast_reference_datetime',
            field=models.DateTimeField(
                blank=True,
                help_text=
                "The reference datetime: i.e. predictions for times after this point occur in the future. Predictions prior to this time represent 'hindcasts', predicting states that have already occurred. This must be in UTC. It is formatted like '2022-08-12T00:00:00Z'.",
                null=True
            ),
        ),
    ]
