# Generated by Django 5.0.8 on 2024-11-11 15:08

from django.db import migrations
from django.db import models

import stac_api.validators


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0054_item_forecast_reference_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='forecast_horizon',
            field=models.CharField(
                blank=True,
                help_text=
                'The time between the reference datetime and the forecast datetime. Formatted as ISO 8601 duration, e.g. PT6H for a 6-hour forecast.',
                null=True,
                validators=[stac_api.validators.validate_iso_8601_duration]
            ),
        ),
    ]
