# Generated by Django 5.0.8 on 2024-11-28 13:20

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0054_update_conformance_endpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='forecast_duration',
            field=models.DurationField(
                blank=True,
                help_text=
                "If the forecast is not only for a specific instance in time but instead is for a certain period, you can specify the length here. Formatted as ISO 8601 duration, e.g. 'PT3H' for a 3-hour accumulation. If not given, assumes that the forecast is for an instance in time as if this was set to PT0S (0 seconds).",
                null=True
            ),
        ),
        migrations.AddField(
            model_name='item',
            name='forecast_horizon',
            field=models.DurationField(
                blank=True,
                help_text=
                "The time between the reference datetime and the forecast datetime.Formatted as ISO 8601 duration, e.g. 'PT6H' for a 6-hour forecast.",
                null=True
            ),
        ),
        migrations.AddField(
            model_name='item',
            name='forecast_mode',
            field=models.CharField(
                blank=True,
                choices=[('ctrl', 'Control run'), ('perturb', 'Perturbed run')],
                default=None,
                help_text=
                'Denotes whether the data corresponds to the control run or perturbed runs.',
                null=True
            ),
        ),
        migrations.AddField(
            model_name='item',
            name='forecast_param',
            field=models.CharField(
                blank=True,
                help_text=
                'Name of the model parameter that corresponds to the data, e.g. `T` (temperature), `P` (pressure), `U`/`V`/`W` (windspeed in three directions).',
                null=True
            ),
        ),
        migrations.AddField(
            model_name='item',
            name='forecast_reference_datetime',
            field=models.DateTimeField(
                blank=True,
                help_text=
                "The reference datetime: i.e. predictions for times after this point occur in the future. Predictions prior to this time represent 'hindcasts', predicting states that have already occurred. This must be in UTC. It is formatted like '2022-08-12T00:00:00Z'.",
                null=True
            ),
        ),
    ]
