# Generated by Django 5.0.8 on 2024-11-11 15:48

from django.db import migrations
from django.db import models

import stac_api.validators


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0055_item_forecast_horizon'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='forecast_duration',
            field=models.CharField(
                blank=True,
                help_text=
                'If the forecast is not only for a specific instance in time but instead is for a certain period, you can specify the length here. Formatted as ISO 8601 duration, e.g. PT3H for a 3-hour accumulation.',
                null=True
            ),
        ),
    ]
