# Generated by Django 5.0.8 on 2024-11-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0057_item_forecast_mode_item_forecast_param'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='forecast_duration',
            field=models.DurationField(blank=True, help_text='If the forecast is not only for a specific instance in time but instead is for a certain period, you can specify the length here.', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='forecast_horizon',
            field=models.DurationField(blank=True, help_text='The time between the reference datetime and the forecast datetime.', null=True),
        ),
    ]
