# Generated by Django 5.0.8 on 2025-01-15 13:08

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0059_alter_asset_media_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='forecast_perturbed',
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text=
                'Denotes whether the data corresponds to the control run (`false`) or perturbed runs (`true`). The property needs to be specified in both cases as no default value is specified and as such the meaning is "unknown" in case it\'s missing.',
                null=True
            ),
        ),
        migrations.AddField(
            model_name='item',
            name='forecast_variable',
            field=models.CharField(
                blank=True,
                help_text=
                'Name of the model variable that corresponds to the data. The variables should correspond to the [CF Standard Names](https://cfconventions.org/Data/cf-standard-names/current/build/cf-standard-name-table.html), e.g. `air_temperature` for the air temperature.',
                null=True
            ),
        ),
    ]
