# Generated by Django 5.0.8 on 2025-01-15 14:23

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0060_item_forecast_perturbed_item_forecast_variable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='forecast_mode',
        ),
        migrations.RemoveField(
            model_name='item',
            name='forecast_param',
        ),
        migrations.AlterField(
            model_name='item',
            name='forecast_variable',
            field=models.CharField(
                blank=True,
                help_text=
                'Name of the model variable that corresponds to the data. The variables should correspond to the CF Standard Names, e.g. `air_temperature` for the air temperature.',
                null=True
            ),
        ),
    ]
