# Generated by Django 5.0.11 on 2025-01-27 08:22

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0061_remove_item_forecast_mode_remove_item_forecast_param_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='item',
            index=models.Index(
                fields=['forecast_reference_datetime'], name='item_fc_reference_datetime_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['forecast_horizon'], name='item_fc_horizon_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['forecast_duration'], name='item_fc_duration_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['forecast_variable'], name='item_fc_variable_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['forecast_perturbed'], name='item_fc_perturbed_idx'),
        ),
    ]
