# Generated by Django 5.0.11 on 2025-03-06 09:14

from django.db import migrations
from django.db import models

import stac_api.validators


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0062_item_item_fc_reference_datetime_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='cache_control_header',
            field=models.CharField(
                blank=True,
                help_text=
                'Cache-Control header value to use for this collection. When set it override the default cache control header value for all API call related to the collection as well as for the data download call.',
                max_length=255,
                null=True,
                validators=[stac_api.validators.validate_cache_control_header]
            ),
        ),
    ]
