# Generated by Django 5.0.11 on 2025-03-19 11:09

import django.core.validators
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0064_alter_asset_media_type_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='asset',
            name='add_del_asset_item_update_interval_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='asset',
            name='update_asset_item_update_interval_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='collectionasset',
            name='add_del_col_asset_col_update_interval_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='collectionasset',
            name='update_col_asset_col_update_interval_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='item',
            name='add_del_item_collection_update_interval_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='item',
            name='update_item_collection_update_interval_trigger',
        ),
        migrations.RemoveIndex(
            model_name='item',
            name='item_update_interval_idx',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='update_interval',
        ),
        migrations.RemoveField(
            model_name='item',
            name='update_interval',
        ),
        migrations.AddField(
            model_name='collectionasset',
            name='is_external',
            field=models.BooleanField(default=False, help_text='Whether this asset is hosted externally'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='update_interval',
            field=models.IntegerField(default=-1, help_text='<b>DEPRECATED FIELD, has no effect anymore. </b></br>Interval in seconds in which the asset data is updated. -1 means that the data is not on a regular basis updated.', validators=[django.core.validators.MinValueValidator(-1)]),
        ),
        migrations.AlterField(
            model_name='assetupload',
            name='update_interval',
            field=models.IntegerField(default=-1, help_text='<b>DEPRECATED FIELD, has no effect anymore. </b></br>Interval in seconds in which the asset data is updated. -1 means that the data is not on a regular basis updated. This field can only be set via the API.', validators=[django.core.validators.MinValueValidator(-1)]),
        ),
        migrations.AlterField(
            model_name='collectionasset',
            name='update_interval',
            field=models.IntegerField(default=-1, help_text='<b>DEPRECATED FIELD, has no effect anymore. </b></br>Interval in seconds in which the asset data is updated. -1 means that the data is not on a regular basis updated.', validators=[django.core.validators.MinValueValidator(-1)]),
        ),
        migrations.AlterField(
            model_name='collectionassetupload',
            name='update_interval',
            field=models.IntegerField(default=-1, help_text='<b>DEPRECATED FIELD, has no effect anymore. </b></br>Interval in seconds in which the asset data is updated. -1 means that the data is not on a regular basis updated. This field can only be set via the API.', validators=[django.core.validators.MinValueValidator(-1)]),
        ),
    ]
