# Generated by Django 5.0.11 on 2025-03-19 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0065_collectionasset_is_external'),
        ('stac_api', '0065_remove_asset_add_del_asset_item_update_interval_trigger_and_more'),
    ]

    operations = []
