# Generated by Django 5.0.11 on 2025-03-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0065_remove_asset_add_del_asset_item_update_interval_trigger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionasset',
            name='is_external',
            field=models.BooleanField(default=False, help_text='Whether this asset is hosted externally'),
        ),
    ]
