# Generated by Django 5.2.11 on 2026-05-29 07:44

import pgtrigger.compiler
import pgtrigger.migrations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0070_alter_asset_media_type_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='asset',
            name='update_asset_auto_variables_trigger',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='asset',
            trigger=pgtrigger.compiler.Trigger(
                name='update_asset_auto_variables_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition=
                    'WHEN (OLD."checksum_multihash" IS DISTINCT FROM (NEW."checksum_multihash") OR OLD."file" IS DISTINCT FROM (NEW."file") OR OLD."file_size" IS DISTINCT FROM (NEW."file_size"))',
                    func=
                    "\n    -- update auto variables\n    NEW.etag = gen_random_uuid();\n    NEW.updated = now();\n\n    RAISE INFO 'Updated auto fields of %.id=% due to table updates.', TG_TABLE_NAME, NEW.id;\n\n    RETURN NEW;\n    ",
                    hash='fe11ac7b1df766190abf538f13ffa2c07ffcf3c9',
                    operation='UPDATE',
                    pgid='pgtrigger_update_asset_auto_variables_trigger_003e1',
                    table='stac_api_asset',
                    when='BEFORE'
                )
            ),
        ),
    ]
