# Generated by Django 5.2.11 on 2026-06-03 06:08

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0070_alter_asset_media_type_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='asset',
            name='update_asset_item_file_size_trigger',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='asset',
            trigger=pgtrigger.compiler.Trigger(name='update_asset_item_file_size_trigger', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."file_size" IS DISTINCT FROM (NEW."file_size"))', declare='DECLARE asset_instance stac_api_asset%ROWTYPE; updated_total_data_size NUMERIC;', func="\n        asset_instance = COALESCE(NEW, OLD);\n\n        -- Update related item file_size variables\n        UPDATE stac_api_item SET\n            total_data_size = total_data_size + COALESCE(NEW.file_size, 0) - COALESCE(OLD.file_size, 0)\n        WHERE id = asset_instance.item_id\n        RETURNING total_data_size INTO updated_total_data_size;\n\n        IF updated_total_data_size < 0\n            THEN RAISE WARNING 'item.id=% total_data_size has negative value %',\n            asset_instance.item_id, updated_total_data_size;\n        END IF;\n\n        RAISE INFO 'item.id=% total_data_size updated, due to asset.name=% updates.',\n            asset_instance.item_id, asset_instance.name;\n\n        RETURN asset_instance;\n        ", hash='2e0243f743d6b4ba265e71d9a738d73551d84431', operation='UPDATE', pgid='pgtrigger_update_asset_item_file_size_trigger_316e8', table='stac_api_asset', when='AFTER')),
        ),
    ]
