# Generated by Django 5.2.11 on 2026-06-03 06:12

import pgtrigger.compiler
import pgtrigger.migrations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0071_remove_asset_update_asset_item_file_size_trigger_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='collectionasset',
            name='upd_dec_col_asset_proj_epsg_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='collectionasset',
            name='upd_inc_col_asset_proj_epsg_trigger',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='collectionasset',
            trigger=pgtrigger.compiler.Trigger(
                name='upd_dec_col_asset_proj_epsg_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."proj_epsg" IS DISTINCT FROM (NEW."proj_epsg"))',
                    declare=
                    'DECLARE asset_instance stac_api_collectionasset%ROWTYPE; related_collection_id INT;',
                    func=
                    "\n        asset_instance = OLD;\n\n        related_collection_id = asset_instance.collection_id;\n\n        -- Remove entry when count will reach 0\n        DELETE FROM stac_api_projepsgcount\n        WHERE collection_id = related_collection_id\n            AND value = asset_instance.proj_epsg\n            AND count = 1;\n\n        IF NOT FOUND THEN\n        UPDATE stac_api_projepsgcount\n        SET count = count-1\n        WHERE collection_id = related_collection_id\n            AND value = asset_instance.proj_epsg;\n\n        RAISE INFO\n            'stac_api_projepsgcount (collection_id, value) (% %) count updated, due to asset.name=% update.',\n            related_collection_id, asset_instance.proj_epsg, asset_instance.name;\n\n        RETURN asset_instance;\n        END IF;\n\n        RAISE INFO\n            'stac_api_projepsgcount (collection_id, value) (% %) deleted, due to asset.name=% update.',\n            related_collection_id, asset_instance.proj_epsg, asset_instance.name;\n\n        RETURN asset_instance;\n        ",
                    hash='56e4e1fae63cd83c85410bb5e49f1672f644c015',
                    operation='UPDATE',
                    pgid='pgtrigger_upd_dec_col_asset_proj_epsg_trigger_07a9d',
                    table='stac_api_collectionasset',
                    when='AFTER'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='collectionasset',
            trigger=pgtrigger.compiler.Trigger(
                name='upd_inc_col_asset_proj_epsg_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."proj_epsg" IS DISTINCT FROM (NEW."proj_epsg"))',
                    declare=
                    'DECLARE asset_instance stac_api_collectionasset%ROWTYPE; related_collection_id INT;',
                    func=
                    "\n        asset_instance = NEW;\n\n        related_collection_id = asset_instance.collection_id;\n\n        INSERT INTO stac_api_projepsgcount (collection_id, value, count)\n        VALUES (related_collection_id, asset_instance.proj_epsg, 1)\n        ON CONFLICT (collection_id, value)\n        DO UPDATE SET count = stac_api_projepsgcount.count+1;\n\n        RAISE INFO\n            'projepsgcount (collection_id, value) (% %) count updated, due to asset.name=% update.',\n            related_collection_id, asset_instance.proj_epsg, asset_instance.name;\n\n        RETURN asset_instance;\n        ",
                    hash='0626a8387cba7cffb40dd81594e3d5c5c16e9ea4',
                    operation='UPDATE',
                    pgid='pgtrigger_upd_inc_col_asset_proj_epsg_trigger_d717d',
                    table='stac_api_collectionasset',
                    when='AFTER'
                )
            ),
        ),
    ]
