# Generated by Django 5.2.11 on 2026-06-03 10:52

import pgtrigger.compiler
import pgtrigger.migrations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0072_remove_collectionasset_upd_dec_col_asset_proj_epsg_trigger_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='asset',
            name='update_asset_auto_variables_trigger',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='asset',
            trigger=pgtrigger.compiler.Trigger(
                name='update_asset_auto_variables_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition=
                    'WHEN (OLD."checksum_multihash" IS DISTINCT FROM (NEW."checksum_multihash") OR OLD."file" IS DISTINCT FROM (NEW."file"))',
                    func=
                    "\n    -- update auto variables\n    NEW.etag = gen_random_uuid();\n    NEW.updated = now();\n\n    RAISE INFO 'Updated auto fields of %.id=% due to table updates.', TG_TABLE_NAME, NEW.id;\n\n    RETURN NEW;\n    ",
                    hash='ec15994d80ec852d8e7d8aa3b50a915b49a32a2e',
                    operation='UPDATE',
                    pgid='pgtrigger_update_asset_auto_variables_trigger_003e1',
                    table='stac_api_asset',
                    when='BEFORE'
                )
            ),
        ),
    ]
