# Generated by Django 5.2.11 on 2026-06-03 06:16

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0072_remove_collectionasset_upd_dec_col_asset_proj_epsg_trigger_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='collectionasset',
            name='update_col_asset_col_file_size_trigger',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='collectionasset',
            trigger=pgtrigger.compiler.Trigger(name='update_col_asset_col_file_size_trigger', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."file_size" IS DISTINCT FROM (NEW."file_size"))', declare='DECLARE asset_instance stac_api_collectionasset%ROWTYPE; updated_total_data_size NUMERIC;', func="\n        asset_instance = COALESCE(NEW, OLD);\n\n        -- Update related collection file_size variables\n        UPDATE stac_api_collection SET\n            total_data_size = total_data_size + COALESCE(NEW.file_size, 0) - COALESCE(OLD.file_size, 0)\n        WHERE id = asset_instance.collection_id\n        RETURNING total_data_size INTO updated_total_data_size;\n\n        IF updated_total_data_size < 0\n            THEN RAISE WARNING 'item.id=% total_data_size has negative value %',\n            asset_instance.collection_id, updated_total_data_size;\n        END IF;\n\n        RAISE INFO 'collection.id=% total_data_size updated, due to item.name=% updates.',\n            asset_instance.collection_id, asset_instance.name;\n\n        RETURN asset_instance;\n        ", hash='dcdfcb6be3790438160ca724d96d0456ca68276d', operation='UPDATE', pgid='pgtrigger_update_col_asset_col_file_size_trigger_1d5be', table='stac_api_collectionasset', when='AFTER')),
        ),
    ]
