# Generated by Django 5.2.11 on 2026-06-09 15:00

import pgtrigger.compiler
import pgtrigger.migrations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0073_remove_asset_update_asset_auto_variables_trigger_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='asset',
            name='add_asset_auto_variables_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='asset',
            name='update_asset_auto_variables_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='collection',
            name='add_collection_auto_variables_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='collection',
            name='update_collection_auto_variables_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='collectionasset',
            name='add_col_asset_auto_variables_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='collectionasset',
            name='update_col_asset_auto_variables_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='item',
            name='add_item_auto_variables_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='item',
            name='update_item_auto_variables_trigger',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='asset',
            trigger=pgtrigger.compiler.Trigger(
                name='add_asset_auto_variables_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func=
                    "NEW.etag = gen_random_uuid();NEW.updated = now();\nRAISE INFO 'Updated auto fields of %.id=% due to table updates.', TG_TABLE_NAME, NEW.id;\nRETURN NEW;\n",
                    hash='d0575b20c3dd01069ba76face45677562261b07e',
                    operation='INSERT',
                    pgid='pgtrigger_add_asset_auto_variables_trigger_307cc',
                    table='stac_api_asset',
                    when='BEFORE'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='asset',
            trigger=pgtrigger.compiler.Trigger(
                name='update_asset_timestamp_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition=
                    'WHEN (OLD."checksum_multihash" IS DISTINCT FROM (NEW."checksum_multihash") OR OLD."file" IS DISTINCT FROM (NEW."file"))',
                    func=
                    "NEW.updated = now();\nRAISE INFO 'Updated auto fields of %.id=% due to table updates.', TG_TABLE_NAME, NEW.id;\nRETURN NEW;\n",
                    hash='04ae7d47735672a7ef6adfabbb21ee1ff3309eec',
                    operation='UPDATE',
                    pgid='pgtrigger_update_asset_timestamp_trigger_8db08',
                    table='stac_api_asset',
                    when='BEFORE'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='asset',
            trigger=pgtrigger.compiler.Trigger(
                name='update_asset_etag_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)',
                    func=
                    "NEW.etag = gen_random_uuid();\nRAISE INFO 'Updated auto fields of %.id=% due to table updates.', TG_TABLE_NAME, NEW.id;\nRETURN NEW;\n",
                    hash='af1a6c1fba377dd5e7e1758380aafebb44beb1dd',
                    operation='UPDATE',
                    pgid='pgtrigger_update_asset_etag_trigger_002d3',
                    table='stac_api_asset',
                    when='BEFORE'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='collection',
            trigger=pgtrigger.compiler.Trigger(
                name='add_collection_auto_variables_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func=
                    "NEW.etag = gen_random_uuid();NEW.updated = now();\nRAISE INFO 'Updated auto fields of %.id=% due to table updates.', TG_TABLE_NAME, NEW.id;\nRETURN NEW;\n",
                    hash='44ef922fa07d06f61f2f91aed7e59da7f7ad5dff',
                    operation='INSERT',
                    pgid='pgtrigger_add_collection_auto_variables_trigger_c2d7a',
                    table='stac_api_collection',
                    when='BEFORE'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='collection',
            trigger=pgtrigger.compiler.Trigger(
                name='update_collection_timestamp_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)',
                    func=
                    "NEW.updated = now();\nRAISE INFO 'Updated auto fields of %.id=% due to table updates.', TG_TABLE_NAME, NEW.id;\nRETURN NEW;\n",
                    hash='42cbc51a438a6fdfb2eaa23c7dc09b96c310d7a4',
                    operation='UPDATE',
                    pgid='pgtrigger_update_collection_timestamp_trigger_2f4db',
                    table='stac_api_collection',
                    when='BEFORE'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='collection',
            trigger=pgtrigger.compiler.Trigger(
                name='update_collection_etag_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)',
                    func=
                    "NEW.etag = gen_random_uuid();\nRAISE INFO 'Updated auto fields of %.id=% due to table updates.', TG_TABLE_NAME, NEW.id;\nRETURN NEW;\n",
                    hash='29c12a8ef02ee5856661cedd0388f5fe464be36f',
                    operation='UPDATE',
                    pgid='pgtrigger_update_collection_etag_trigger_e0f93',
                    table='stac_api_collection',
                    when='BEFORE'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='collectionasset',
            trigger=pgtrigger.compiler.Trigger(
                name='add_col_asset_auto_variables_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func=
                    "NEW.etag = gen_random_uuid();NEW.updated = now();\nRAISE INFO 'Updated auto fields of %.id=% due to table updates.', TG_TABLE_NAME, NEW.id;\nRETURN NEW;\n",
                    hash='10937211cf3231826744faa9d542ee06a24f525b',
                    operation='INSERT',
                    pgid='pgtrigger_add_col_asset_auto_variables_trigger_1ff98',
                    table='stac_api_collectionasset',
                    when='BEFORE'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='collectionasset',
            trigger=pgtrigger.compiler.Trigger(
                name='update_col_asset_timestamp_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)',
                    func=
                    "NEW.updated = now();\nRAISE INFO 'Updated auto fields of %.id=% due to table updates.', TG_TABLE_NAME, NEW.id;\nRETURN NEW;\n",
                    hash='65121c471fbf9e5a51b9c437abb9d17fc3934ae2',
                    operation='UPDATE',
                    pgid='pgtrigger_update_col_asset_timestamp_trigger_5bcc9',
                    table='stac_api_collectionasset',
                    when='BEFORE'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='collectionasset',
            trigger=pgtrigger.compiler.Trigger(
                name='update_col_asset_etag_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)',
                    func=
                    "NEW.etag = gen_random_uuid();\nRAISE INFO 'Updated auto fields of %.id=% due to table updates.', TG_TABLE_NAME, NEW.id;\nRETURN NEW;\n",
                    hash='9baa8933f36ad352114f18e8cda7902ed1f43425',
                    operation='UPDATE',
                    pgid='pgtrigger_update_col_asset_etag_trigger_662ff',
                    table='stac_api_collectionasset',
                    when='BEFORE'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='item',
            trigger=pgtrigger.compiler.Trigger(
                name='add_item_auto_variables_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func=
                    "NEW.etag = gen_random_uuid();NEW.updated = now();\nRAISE INFO 'Updated auto fields of %.id=% due to table updates.', TG_TABLE_NAME, NEW.id;\nRETURN NEW;\n",
                    hash='c27931e2591392c5d7bc5fc7e03dcd3a970d0ab0',
                    operation='INSERT',
                    pgid='pgtrigger_add_item_auto_variables_trigger_09b8c',
                    table='stac_api_item',
                    when='BEFORE'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='item',
            trigger=pgtrigger.compiler.Trigger(
                name='update_item_timestamp_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)',
                    func=
                    "NEW.updated = now();\nRAISE INFO 'Updated auto fields of %.id=% due to table updates.', TG_TABLE_NAME, NEW.id;\nRETURN NEW;\n",
                    hash='272e7a52faceb87e64f2353048c918b3aa01649b',
                    operation='UPDATE',
                    pgid='pgtrigger_update_item_timestamp_trigger_729c3',
                    table='stac_api_item',
                    when='BEFORE'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='item',
            trigger=pgtrigger.compiler.Trigger(
                name='update_item_etag_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)',
                    func=
                    "NEW.etag = gen_random_uuid();\nRAISE INFO 'Updated auto fields of %.id=% due to table updates.', TG_TABLE_NAME, NEW.id;\nRETURN NEW;\n",
                    hash='83629c28291715bff86cfe0118b258ee26b1ac22',
                    operation='UPDATE',
                    pgid='pgtrigger_update_item_etag_trigger_ce016',
                    table='stac_api_item',
                    when='BEFORE'
                )
            ),
        ),
    ]
