# Generated by Django 5.2.11 on 2026-06-03 11:46

import pgtrigger.compiler
import pgtrigger.migrations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0073_remove_asset_update_asset_auto_variables_trigger_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='asset',
            name='update_item_child_trigger',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='asset',
            trigger=pgtrigger.compiler.Trigger(
                name='update_item_child_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."updated" IS DISTINCT FROM (NEW."updated"))',
                    func=
                    "\n    -- update related item\n    UPDATE stac_api_item SET\n        updated = now(),\n        etag = public.gen_random_uuid()\n    WHERE id = NEW.item_id;\n\n    RAISE INFO 'Parent table item.id=% auto fields updated due to child Asset.id=% updates.',\n        NEW.item_id, NEW.id;\n\n    RETURN NEW;\n    ",
                    hash='4dd699496e921d5be8c809a22a973a19bdac190e',
                    operation='UPDATE',
                    pgid='pgtrigger_update_item_child_trigger_15ed4',
                    table='stac_api_asset',
                    when='AFTER'
                )
            ),
        ),
    ]
