# Generated by Django 5.2.11 on 2026-06-09 14:31

import pgtrigger.compiler
import pgtrigger.migrations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0073_remove_asset_update_asset_auto_variables_trigger_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='asset',
            name='add_asset_auto_variables_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='asset',
            name='update_asset_auto_variables_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='collection',
            name='add_collection_auto_variables_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='collection',
            name='update_collection_auto_variables_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='collectionasset',
            name='add_col_asset_auto_variables_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='collectionasset',
            name='update_col_asset_auto_variables_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='item',
            name='add_item_auto_variables_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='item',
            name='update_item_auto_variables_trigger',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='asset',
            trigger=pgtrigger.compiler.Trigger(
                name='add_asset_auto_variables_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func=
                    "NEW.etag = gen_random_uuid();NEW.updated = now();\n    RAISE INFO 'Updated auto fields of %.id=% due to table updates.', TG_TABLE_NAME, NEW.id;\n    RETURN NEW;\n    ",
                    hash='e286d674a2e6b3788fd619b31bbdc563dcc93580',
                    operation='INSERT',
                    pgid='pgtrigger_add_asset_auto_variables_trigger_307cc',
                    table='stac_api_asset',
                    when='BEFORE'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='asset',
            trigger=pgtrigger.compiler.Trigger(
                name='update_asset_timestamp_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition=
                    'WHEN (OLD."checksum_multihash" IS DISTINCT FROM (NEW."checksum_multihash") OR OLD."file" IS DISTINCT FROM (NEW."file"))',
                    func=
                    "NEW.updated = now();\n    RAISE INFO 'Updated auto fields of %.id=% due to table updates.', TG_TABLE_NAME, NEW.id;\n    RETURN NEW;\n    ",
                    hash='1c0851b99c4347cc6e666d8cdc29eebad40c84cf',
                    operation='UPDATE',
                    pgid='pgtrigger_update_asset_timestamp_trigger_8db08',
                    table='stac_api_asset',
                    when='BEFORE'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='asset',
            trigger=pgtrigger.compiler.Trigger(
                name='update_asset_etag_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)',
                    func=
                    "NEW.etag = gen_random_uuid();\n    RAISE INFO 'Updated auto fields of %.id=% due to table updates.', TG_TABLE_NAME, NEW.id;\n    RETURN NEW;\n    ",
                    hash='e3ccfd803c7e2434c849cc69b6ad7910ea8d0ddc',
                    operation='UPDATE',
                    pgid='pgtrigger_update_asset_etag_trigger_002d3',
                    table='stac_api_asset',
                    when='BEFORE'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='collection',
            trigger=pgtrigger.compiler.Trigger(
                name='add_collection_auto_variables_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func=
                    "NEW.etag = gen_random_uuid();NEW.updated = now();\n    RAISE INFO 'Updated auto fields of %.id=% due to table updates.', TG_TABLE_NAME, NEW.id;\n    RETURN NEW;\n    ",
                    hash='759dec167e7b90a384a11a52544fd08c71ba403b',
                    operation='INSERT',
                    pgid='pgtrigger_add_collection_auto_variables_trigger_c2d7a',
                    table='stac_api_collection',
                    when='BEFORE'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='collection',
            trigger=pgtrigger.compiler.Trigger(
                name='update_collection_timestamp_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)',
                    func=
                    "NEW.updated = now();\n    RAISE INFO 'Updated auto fields of %.id=% due to table updates.', TG_TABLE_NAME, NEW.id;\n    RETURN NEW;\n    ",
                    hash='66f4f855519ec974185df2ff32b113a6cf2da5dc',
                    operation='UPDATE',
                    pgid='pgtrigger_update_collection_timestamp_trigger_2f4db',
                    table='stac_api_collection',
                    when='BEFORE'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='collection',
            trigger=pgtrigger.compiler.Trigger(
                name='update_collection_etag_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)',
                    func=
                    "NEW.etag = gen_random_uuid();\n    RAISE INFO 'Updated auto fields of %.id=% due to table updates.', TG_TABLE_NAME, NEW.id;\n    RETURN NEW;\n    ",
                    hash='e483de7d469e6e6d3432caf8245da4e71fc6c749',
                    operation='UPDATE',
                    pgid='pgtrigger_update_collection_etag_trigger_e0f93',
                    table='stac_api_collection',
                    when='BEFORE'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='collectionasset',
            trigger=pgtrigger.compiler.Trigger(
                name='add_col_asset_auto_variables_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func=
                    "NEW.etag = gen_random_uuid();NEW.updated = now();\n    RAISE INFO 'Updated auto fields of %.id=% due to table updates.', TG_TABLE_NAME, NEW.id;\n    RETURN NEW;\n    ",
                    hash='b0ae9e7ca5f64a30afb7a36a726cb4eca83a228c',
                    operation='INSERT',
                    pgid='pgtrigger_add_col_asset_auto_variables_trigger_1ff98',
                    table='stac_api_collectionasset',
                    when='BEFORE'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='collectionasset',
            trigger=pgtrigger.compiler.Trigger(
                name='update_col_asset_timestamp_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)',
                    func=
                    "NEW.updated = now();\n    RAISE INFO 'Updated auto fields of %.id=% due to table updates.', TG_TABLE_NAME, NEW.id;\n    RETURN NEW;\n    ",
                    hash='86039c6ea846bda23b19c264730c55510f1ac36a',
                    operation='UPDATE',
                    pgid='pgtrigger_update_col_asset_timestamp_trigger_5bcc9',
                    table='stac_api_collectionasset',
                    when='BEFORE'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='collectionasset',
            trigger=pgtrigger.compiler.Trigger(
                name='update_col_asset_etag_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)',
                    func=
                    "NEW.etag = gen_random_uuid();\n    RAISE INFO 'Updated auto fields of %.id=% due to table updates.', TG_TABLE_NAME, NEW.id;\n    RETURN NEW;\n    ",
                    hash='c287ae0aa9c1c704d801600d2c320df5ba9f4623',
                    operation='UPDATE',
                    pgid='pgtrigger_update_col_asset_etag_trigger_662ff',
                    table='stac_api_collectionasset',
                    when='BEFORE'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='item',
            trigger=pgtrigger.compiler.Trigger(
                name='add_item_auto_variables_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func=
                    "NEW.etag = gen_random_uuid();NEW.updated = now();\n    RAISE INFO 'Updated auto fields of %.id=% due to table updates.', TG_TABLE_NAME, NEW.id;\n    RETURN NEW;\n    ",
                    hash='9ea93d026f45d04ab67e8b51c725bb434a24ee94',
                    operation='INSERT',
                    pgid='pgtrigger_add_item_auto_variables_trigger_09b8c',
                    table='stac_api_item',
                    when='BEFORE'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='item',
            trigger=pgtrigger.compiler.Trigger(
                name='update_item_timestamp_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)',
                    func=
                    "NEW.updated = now();\n    RAISE INFO 'Updated auto fields of %.id=% due to table updates.', TG_TABLE_NAME, NEW.id;\n    RETURN NEW;\n    ",
                    hash='5a242899d0b24bd52808603acc559063dd863984',
                    operation='UPDATE',
                    pgid='pgtrigger_update_item_timestamp_trigger_729c3',
                    table='stac_api_item',
                    when='BEFORE'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='item',
            trigger=pgtrigger.compiler.Trigger(
                name='update_item_etag_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)',
                    func=
                    "NEW.etag = gen_random_uuid();\n    RAISE INFO 'Updated auto fields of %.id=% due to table updates.', TG_TABLE_NAME, NEW.id;\n    RETURN NEW;\n    ",
                    hash='b39a383ca70b2360101c8f4c270e865b84cf8784',
                    operation='UPDATE',
                    pgid='pgtrigger_update_item_etag_trigger_ce016',
                    table='stac_api_item',
                    when='BEFORE'
                )
            ),
        ),
    ]
