# Generated by Django 5.2.11 on 2026-06-10 11:38

import pgtrigger.compiler
import pgtrigger.migrations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0074_remove_asset_add_asset_auto_variables_trigger_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='collection',
            name='update_collection_timestamp_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='collectionasset',
            name='update_col_asset_timestamp_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='item',
            name='update_item_timestamp_trigger',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='collectionasset',
            trigger=pgtrigger.compiler.Trigger(
                name='update_col_asset_timestamp_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition=
                    'WHEN (OLD."checksum_multihash" IS DISTINCT FROM (NEW."checksum_multihash") OR OLD."file" IS DISTINCT FROM (NEW."file"))',
                    func=
                    "NEW.updated = now();\nRAISE INFO 'Updated auto fields of %.id=% due to table updates.', TG_TABLE_NAME, NEW.id;\nRETURN NEW;\n",
                    hash='61e9646304f88d1b4e9bd50e181bb5d0c5963087',
                    operation='UPDATE',
                    pgid='pgtrigger_update_col_asset_timestamp_trigger_5bcc9',
                    table='stac_api_collectionasset',
                    when='BEFORE'
                )
            ),
        ),
    ]
