# Generated by Django 5.2.11 on 2026-06-10 12:42

import pgtrigger.compiler
import pgtrigger.migrations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0075_remove_collection_update_collection_timestamp_trigger_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='asset',
            name='add_item_child_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='asset',
            name='update_item_child_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='asset',
            name='del_item_child_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='collectionasset',
            name='add_collection_child_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='collectionasset',
            name='update_collection_child_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='collectionasset',
            name='del_collection_child_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='collectionlink',
            name='add_collection_child_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='collectionlink',
            name='update_collection_child_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='collectionlink',
            name='del_collection_child_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='item',
            name='add_collection_child_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='item',
            name='update_collection_child_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='item',
            name='del_collection_child_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='itemlink',
            name='add_item_child_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='itemlink',
            name='update_item_child_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='itemlink',
            name='del_item_child_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='provider',
            name='add_collection_child_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='provider',
            name='update_collection_child_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='provider',
            name='del_collection_child_trigger',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='asset',
            trigger=pgtrigger.compiler.Trigger(
                name='add_or_del_item_child_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    declare='DECLARE child stac_api_Asset%ROWTYPE;',
                    func=
                    "\n-- update related item\nchild = COALESCE(NEW, OLD);\nUPDATE stac_api_item SET\n    etag = public.gen_random_uuid(), updated = now()\nWHERE id = child.item_id;\n\nRAISE INFO 'Parent table item.id=% auto fields updated due to child Asset.id=% updates.',\n    child.item_id, child.id;\n\nRETURN child;\n",
                    hash='6c8d1f42bfba9e5f4151798d4f9e3c889a5bc536',
                    operation='INSERT OR DELETE',
                    pgid='pgtrigger_add_or_del_item_child_trigger_18252',
                    table='stac_api_asset',
                    when='AFTER'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='asset',
            trigger=pgtrigger.compiler.Trigger(
                name='update_item_child_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."updated" IS DISTINCT FROM (NEW."updated"))',
                    declare='DECLARE child stac_api_Asset%ROWTYPE;',
                    func=
                    "\n-- update related item\nchild = COALESCE(NEW, OLD);\nUPDATE stac_api_item SET\n    etag = public.gen_random_uuid(), updated = now()\nWHERE id = child.item_id;\n\nRAISE INFO 'Parent table item.id=% auto fields updated due to child Asset.id=% updates.',\n    child.item_id, child.id;\n\nRETURN child;\n",
                    hash='85b271264095e06e868b0b7c5b7a956ec58be45b',
                    operation='UPDATE',
                    pgid='pgtrigger_update_item_child_trigger_15ed4',
                    table='stac_api_asset',
                    when='AFTER'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='asset',
            trigger=pgtrigger.compiler.Trigger(
                name='update_item_child_trigger_etag_only',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition=
                    'WHEN (OLD."checksum_multihash" IS DISTINCT FROM (NEW."checksum_multihash") OR OLD."created" IS DISTINCT FROM (NEW."created") OR OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."eo_gsd" IS DISTINCT FROM (NEW."eo_gsd") OR OLD."etag" IS DISTINCT FROM (NEW."etag") OR OLD."file" IS DISTINCT FROM (NEW."file") OR OLD."file_size" IS DISTINCT FROM (NEW."file_size") OR OLD."geoadmin_lang" IS DISTINCT FROM (NEW."geoadmin_lang") OR OLD."geoadmin_variant" IS DISTINCT FROM (NEW."geoadmin_variant") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."is_external" IS DISTINCT FROM (NEW."is_external") OR OLD."item_id" IS DISTINCT FROM (NEW."item_id") OR OLD."media_type" IS DISTINCT FROM (NEW."media_type") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."proj_epsg" IS DISTINCT FROM (NEW."proj_epsg") OR OLD."roles" IS DISTINCT FROM (NEW."roles") OR OLD."title" IS DISTINCT FROM (NEW."title") OR OLD."update_interval" IS DISTINCT FROM (NEW."update_interval"))',
                    declare='DECLARE child stac_api_Asset%ROWTYPE;',
                    func=
                    "\n-- update related item\nchild = COALESCE(NEW, OLD);\nUPDATE stac_api_item SET\n    etag = public.gen_random_uuid()\nWHERE id = child.item_id;\n\nRAISE INFO 'Parent table item.id=% auto fields updated due to child Asset.id=% updates.',\n    child.item_id, child.id;\n\nRETURN child;\n",
                    hash='111964472ebb8c495c98c947c9c66b999c6fd057',
                    operation='UPDATE',
                    pgid='pgtrigger_update_item_child_trigger_etag_only_03b47',
                    table='stac_api_asset',
                    when='AFTER'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='collectionasset',
            trigger=pgtrigger.compiler.Trigger(
                name='add_or_del_collection_child_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    declare='DECLARE child stac_api_CollectionAsset%ROWTYPE;',
                    func=
                    "\n-- update related collection\nchild = COALESCE(NEW, OLD);\nUPDATE stac_api_collection SET\n    etag = public.gen_random_uuid(), updated = now()\nWHERE id = child.collection_id;\n\nRAISE INFO 'Parent table collection.id=% auto fields updated due to child CollectionAsset.id=% updates.',\n    child.collection_id, child.id;\n\nRETURN child;\n",
                    hash='47d158d82d2dd5e3627852b6b049623ba173fe8b',
                    operation='INSERT OR DELETE',
                    pgid='pgtrigger_add_or_del_collection_child_trigger_5e28a',
                    table='stac_api_collectionasset',
                    when='AFTER'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='collectionasset',
            trigger=pgtrigger.compiler.Trigger(
                name='update_collection_child_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."updated" IS DISTINCT FROM (NEW."updated"))',
                    declare='DECLARE child stac_api_CollectionAsset%ROWTYPE;',
                    func=
                    "\n-- update related collection\nchild = COALESCE(NEW, OLD);\nUPDATE stac_api_collection SET\n    etag = public.gen_random_uuid(), updated = now()\nWHERE id = child.collection_id;\n\nRAISE INFO 'Parent table collection.id=% auto fields updated due to child CollectionAsset.id=% updates.',\n    child.collection_id, child.id;\n\nRETURN child;\n",
                    hash='443890d7c331b3ca2d20536534bace2e75fef707',
                    operation='UPDATE',
                    pgid='pgtrigger_update_collection_child_trigger_ae85d',
                    table='stac_api_collectionasset',
                    when='AFTER'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='collectionasset',
            trigger=pgtrigger.compiler.Trigger(
                name='update_collection_child_trigger_etag_only',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition=
                    'WHEN (OLD."checksum_multihash" IS DISTINCT FROM (NEW."checksum_multihash") OR OLD."collection_id" IS DISTINCT FROM (NEW."collection_id") OR OLD."created" IS DISTINCT FROM (NEW."created") OR OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."etag" IS DISTINCT FROM (NEW."etag") OR OLD."file" IS DISTINCT FROM (NEW."file") OR OLD."file_size" IS DISTINCT FROM (NEW."file_size") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."is_external" IS DISTINCT FROM (NEW."is_external") OR OLD."media_type" IS DISTINCT FROM (NEW."media_type") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."proj_epsg" IS DISTINCT FROM (NEW."proj_epsg") OR OLD."roles" IS DISTINCT FROM (NEW."roles") OR OLD."title" IS DISTINCT FROM (NEW."title") OR OLD."update_interval" IS DISTINCT FROM (NEW."update_interval"))',
                    declare='DECLARE child stac_api_CollectionAsset%ROWTYPE;',
                    func=
                    "\n-- update related collection\nchild = COALESCE(NEW, OLD);\nUPDATE stac_api_collection SET\n    etag = public.gen_random_uuid()\nWHERE id = child.collection_id;\n\nRAISE INFO 'Parent table collection.id=% auto fields updated due to child CollectionAsset.id=% updates.',\n    child.collection_id, child.id;\n\nRETURN child;\n",
                    hash='352f48712cad2d9d2da4425f560e4e8e6f7b0a87',
                    operation='UPDATE',
                    pgid='pgtrigger_update_collection_child_trigger_etag_only_39619',
                    table='stac_api_collectionasset',
                    when='AFTER'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='collectionlink',
            trigger=pgtrigger.compiler.Trigger(
                name='add_or_del_collection_child_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    declare='DECLARE child stac_api_CollectionLink%ROWTYPE;',
                    func=
                    "\n-- update related collection\nchild = COALESCE(NEW, OLD);\nUPDATE stac_api_collection SET\n    etag = public.gen_random_uuid(), updated = now()\nWHERE id = child.collection_id;\n\nRAISE INFO 'Parent table collection.id=% auto fields updated due to child CollectionLink.id=% updates.',\n    child.collection_id, child.id;\n\nRETURN child;\n",
                    hash='d8a1def2f2cc5af56b19074ed629fdd95e9d48cc',
                    operation='INSERT OR DELETE',
                    pgid='pgtrigger_add_or_del_collection_child_trigger_df2ed',
                    table='stac_api_collectionlink',
                    when='AFTER'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='collectionlink',
            trigger=pgtrigger.compiler.Trigger(
                name='update_collection_child_trigger_etag_only',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)',
                    declare='DECLARE child stac_api_CollectionLink%ROWTYPE;',
                    func=
                    "\n-- update related collection\nchild = COALESCE(NEW, OLD);\nUPDATE stac_api_collection SET\n    etag = public.gen_random_uuid()\nWHERE id = child.collection_id;\n\nRAISE INFO 'Parent table collection.id=% auto fields updated due to child CollectionLink.id=% updates.',\n    child.collection_id, child.id;\n\nRETURN child;\n",
                    hash='55f6d5d17745c1e8f521a0bc3d1a12465c329c70',
                    operation='UPDATE',
                    pgid='pgtrigger_update_collection_child_trigger_etag_only_abc6f',
                    table='stac_api_collectionlink',
                    when='AFTER'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='item',
            trigger=pgtrigger.compiler.Trigger(
                name='add_or_del_collection_child_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    declare='DECLARE child stac_api_Item%ROWTYPE;',
                    func=
                    "\n-- update related collection\nchild = COALESCE(NEW, OLD);\nUPDATE stac_api_collection SET\n    etag = public.gen_random_uuid(), updated = now()\nWHERE id = child.collection_id;\n\nRAISE INFO 'Parent table collection.id=% auto fields updated due to child Item.id=% updates.',\n    child.collection_id, child.id;\n\nRETURN child;\n",
                    hash='9be3409b93f34e447ef5c79098286de794acbddb',
                    operation='INSERT OR DELETE',
                    pgid='pgtrigger_add_or_del_collection_child_trigger_bbfb9',
                    table='stac_api_item',
                    when='AFTER'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='item',
            trigger=pgtrigger.compiler.Trigger(
                name='update_collection_child_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."updated" IS DISTINCT FROM (NEW."updated"))',
                    declare='DECLARE child stac_api_Item%ROWTYPE;',
                    func=
                    "\n-- update related collection\nchild = COALESCE(NEW, OLD);\nUPDATE stac_api_collection SET\n    etag = public.gen_random_uuid(), updated = now()\nWHERE id = child.collection_id;\n\nRAISE INFO 'Parent table collection.id=% auto fields updated due to child Item.id=% updates.',\n    child.collection_id, child.id;\n\nRETURN child;\n",
                    hash='a3620d5a35e8b8e906eeb05da23e5c2e28156a77',
                    operation='UPDATE',
                    pgid='pgtrigger_update_collection_child_trigger_c0533',
                    table='stac_api_item',
                    when='AFTER'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='item',
            trigger=pgtrigger.compiler.Trigger(
                name='update_collection_child_trigger_etag_only',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition=
                    'WHEN (OLD."collection_id" IS DISTINCT FROM (NEW."collection_id") OR OLD."created" IS DISTINCT FROM (NEW."created") OR OLD."etag" IS DISTINCT FROM (NEW."etag") OR OLD."forecast_duration" IS DISTINCT FROM (NEW."forecast_duration") OR OLD."forecast_horizon" IS DISTINCT FROM (NEW."forecast_horizon") OR OLD."forecast_perturbed" IS DISTINCT FROM (NEW."forecast_perturbed") OR OLD."forecast_reference_datetime" IS DISTINCT FROM (NEW."forecast_reference_datetime") OR OLD."forecast_variable" IS DISTINCT FROM (NEW."forecast_variable") OR OLD."geometry" IS DISTINCT FROM (NEW."geometry") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."properties_datetime" IS DISTINCT FROM (NEW."properties_datetime") OR OLD."properties_end_datetime" IS DISTINCT FROM (NEW."properties_end_datetime") OR OLD."properties_expires" IS DISTINCT FROM (NEW."properties_expires") OR OLD."properties_start_datetime" IS DISTINCT FROM (NEW."properties_start_datetime") OR OLD."properties_title" IS DISTINCT FROM (NEW."properties_title") OR OLD."total_data_size" IS DISTINCT FROM (NEW."total_data_size"))',
                    declare='DECLARE child stac_api_Item%ROWTYPE;',
                    func=
                    "\n-- update related collection\nchild = COALESCE(NEW, OLD);\nUPDATE stac_api_collection SET\n    etag = public.gen_random_uuid()\nWHERE id = child.collection_id;\n\nRAISE INFO 'Parent table collection.id=% auto fields updated due to child Item.id=% updates.',\n    child.collection_id, child.id;\n\nRETURN child;\n",
                    hash='2a111a512a72cecbe645b1eba73827d6e72bb74f',
                    operation='UPDATE',
                    pgid='pgtrigger_update_collection_child_trigger_etag_only_bee6a',
                    table='stac_api_item',
                    when='AFTER'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='itemlink',
            trigger=pgtrigger.compiler.Trigger(
                name='add_or_del_item_child_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    declare='DECLARE child stac_api_ItemLink%ROWTYPE;',
                    func=
                    "\n-- update related item\nchild = COALESCE(NEW, OLD);\nUPDATE stac_api_item SET\n    etag = public.gen_random_uuid(), updated = now()\nWHERE id = child.item_id;\n\nRAISE INFO 'Parent table item.id=% auto fields updated due to child ItemLink.id=% updates.',\n    child.item_id, child.id;\n\nRETURN child;\n",
                    hash='90f38edcb3bdf7022042df94590d247f263cc70e',
                    operation='INSERT OR DELETE',
                    pgid='pgtrigger_add_or_del_item_child_trigger_ed449',
                    table='stac_api_itemlink',
                    when='AFTER'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='itemlink',
            trigger=pgtrigger.compiler.Trigger(
                name='update_item_child_trigger_etag_only',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)',
                    declare='DECLARE child stac_api_ItemLink%ROWTYPE;',
                    func=
                    "\n-- update related item\nchild = COALESCE(NEW, OLD);\nUPDATE stac_api_item SET\n    etag = public.gen_random_uuid()\nWHERE id = child.item_id;\n\nRAISE INFO 'Parent table item.id=% auto fields updated due to child ItemLink.id=% updates.',\n    child.item_id, child.id;\n\nRETURN child;\n",
                    hash='bc33474e50f6648f2e7793a123c1aeb8f6082b2c',
                    operation='UPDATE',
                    pgid='pgtrigger_update_item_child_trigger_etag_only_26a59',
                    table='stac_api_itemlink',
                    when='AFTER'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='provider',
            trigger=pgtrigger.compiler.Trigger(
                name='add_or_del_collection_child_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    declare='DECLARE child stac_api_Provider%ROWTYPE;',
                    func=
                    "\n-- update related collection\nchild = COALESCE(NEW, OLD);\nUPDATE stac_api_collection SET\n    etag = public.gen_random_uuid(), updated = now()\nWHERE id = child.collection_id;\n\nRAISE INFO 'Parent table collection.id=% auto fields updated due to child Provider.id=% updates.',\n    child.collection_id, child.id;\n\nRETURN child;\n",
                    hash='6a76479817658f6e86f6134467c90549b30728c0',
                    operation='INSERT OR DELETE',
                    pgid='pgtrigger_add_or_del_collection_child_trigger_fed8c',
                    table='stac_api_provider',
                    when='AFTER'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='provider',
            trigger=pgtrigger.compiler.Trigger(
                name='update_collection_child_trigger_etag_only',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)',
                    declare='DECLARE child stac_api_Provider%ROWTYPE;',
                    func=
                    "\n-- update related collection\nchild = COALESCE(NEW, OLD);\nUPDATE stac_api_collection SET\n    etag = public.gen_random_uuid()\nWHERE id = child.collection_id;\n\nRAISE INFO 'Parent table collection.id=% auto fields updated due to child Provider.id=% updates.',\n    child.collection_id, child.id;\n\nRETURN child;\n",
                    hash='28d7954082fba4575fc121a0a9f1c58be7ed113e',
                    operation='UPDATE',
                    pgid='pgtrigger_update_collection_child_trigger_etag_only_33a97',
                    table='stac_api_provider',
                    when='AFTER'
                )
            ),
        ),
    ]
