# Generated by Django 5.2.11 on 2026-06-10 13:37

import pgtrigger.compiler
import pgtrigger.migrations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0076_remove_asset_add_item_child_trigger_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='asset',
            name='add_asset_auto_variables_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='asset',
            name='update_asset_timestamp_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='asset',
            name='update_asset_etag_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='asset',
            name='add_or_del_item_child_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='asset',
            name='update_item_child_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='asset',
            name='update_item_child_trigger_etag_only',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='collection',
            name='add_collection_auto_variables_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='collection',
            name='update_collection_etag_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='collectionasset',
            name='add_col_asset_auto_variables_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='collectionasset',
            name='update_col_asset_etag_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='collectionasset',
            name='update_col_asset_timestamp_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='collectionasset',
            name='add_or_del_collection_child_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='collectionasset',
            name='update_collection_child_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='collectionasset',
            name='update_collection_child_trigger_etag_only',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='collectionlink',
            name='add_or_del_collection_child_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='collectionlink',
            name='update_collection_child_trigger_etag_only',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='item',
            name='add_item_auto_variables_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='item',
            name='update_item_etag_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='item',
            name='add_or_del_collection_child_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='item',
            name='update_collection_child_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='item',
            name='update_collection_child_trigger_etag_only',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='itemlink',
            name='add_or_del_item_child_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='itemlink',
            name='update_item_child_trigger_etag_only',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='provider',
            name='add_or_del_collection_child_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='provider',
            name='update_collection_child_trigger_etag_only',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='asset',
            trigger=pgtrigger.compiler.Trigger(
                name='add_asset_auto_variables_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func=
                    "NEW.etag = gen_random_uuid();NEW.updated = now();\n            RAISE INFO '%: updated % where id=%', TG_NAME, TG_TABLE_NAME, NEW.id;\n            RETURN NEW;\n",
                    hash='a6a55243db852fd805db94d0979c71dd4dd2c838',
                    operation='INSERT',
                    pgid='pgtrigger_add_asset_auto_variables_trigger_307cc',
                    table='stac_api_asset',
                    when='BEFORE'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='asset',
            trigger=pgtrigger.compiler.Trigger(
                name='update_asset_etag_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)',
                    func=
                    "NEW.etag = gen_random_uuid();\n            RAISE INFO '%: updated % where id=%', TG_NAME, TG_TABLE_NAME, NEW.id;\n            RETURN NEW;\n",
                    hash='4a73931c1bcf644adf311d39900df432c8693b53',
                    operation='UPDATE',
                    pgid='pgtrigger_update_asset_etag_trigger_002d3',
                    table='stac_api_asset',
                    when='BEFORE'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='asset',
            trigger=pgtrigger.compiler.Trigger(
                name='update_asset_timestamp_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition=
                    'WHEN (OLD."checksum_multihash" IS DISTINCT FROM (NEW."checksum_multihash") OR OLD."file" IS DISTINCT FROM (NEW."file"))',
                    func=
                    "NEW.updated = now();\n            RAISE INFO '%: updated % where id=%', TG_NAME, TG_TABLE_NAME, NEW.id;\n            RETURN NEW;\n",
                    hash='7c2e2827bba92c2e469121a9d0963e66592f7db1',
                    operation='UPDATE',
                    pgid='pgtrigger_update_asset_timestamp_trigger_8db08',
                    table='stac_api_asset',
                    when='BEFORE'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='asset',
            trigger=pgtrigger.compiler.Trigger(
                name='add_or_del_item_child_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    declare='DECLARE child stac_api_Asset%ROWTYPE;',
                    func=
                    "\n-- update related item\nchild = COALESCE(NEW, OLD);\nUPDATE stac_api_item SET\n    etag = public.gen_random_uuid(), updated = now()\nWHERE id = child.item_id;\n\nRAISE INFO '%: updated item.id=% due to Asset.id=%',\n    TG_NAME, child.item_id, child.id;\n\nRETURN child;\n",
                    hash='4f271111bdb995dcdd4b52e1bd6aa1550b5ecd40',
                    operation='INSERT OR DELETE',
                    pgid='pgtrigger_add_or_del_item_child_trigger_18252',
                    table='stac_api_asset',
                    when='AFTER'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='asset',
            trigger=pgtrigger.compiler.Trigger(
                name='update_item_child_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."updated" IS DISTINCT FROM (NEW."updated"))',
                    declare='DECLARE child stac_api_Asset%ROWTYPE;',
                    func=
                    "\n-- update related item\nchild = COALESCE(NEW, OLD);\nUPDATE stac_api_item SET\n    etag = public.gen_random_uuid(), updated = now()\nWHERE id = child.item_id;\n\nRAISE INFO '%: updated item.id=% due to Asset.id=%',\n    TG_NAME, child.item_id, child.id;\n\nRETURN child;\n",
                    hash='7a368cb5d3f7ede24faa6f0d54a0ce6ccac755f6',
                    operation='UPDATE',
                    pgid='pgtrigger_update_item_child_trigger_15ed4',
                    table='stac_api_asset',
                    when='AFTER'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='asset',
            trigger=pgtrigger.compiler.Trigger(
                name='update_item_child_trigger_etag_only',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition=
                    'WHEN (OLD."checksum_multihash" IS DISTINCT FROM (NEW."checksum_multihash") OR OLD."created" IS DISTINCT FROM (NEW."created") OR OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."eo_gsd" IS DISTINCT FROM (NEW."eo_gsd") OR OLD."etag" IS DISTINCT FROM (NEW."etag") OR OLD."file" IS DISTINCT FROM (NEW."file") OR OLD."file_size" IS DISTINCT FROM (NEW."file_size") OR OLD."geoadmin_lang" IS DISTINCT FROM (NEW."geoadmin_lang") OR OLD."geoadmin_variant" IS DISTINCT FROM (NEW."geoadmin_variant") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."is_external" IS DISTINCT FROM (NEW."is_external") OR OLD."item_id" IS DISTINCT FROM (NEW."item_id") OR OLD."media_type" IS DISTINCT FROM (NEW."media_type") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."proj_epsg" IS DISTINCT FROM (NEW."proj_epsg") OR OLD."roles" IS DISTINCT FROM (NEW."roles") OR OLD."title" IS DISTINCT FROM (NEW."title") OR OLD."update_interval" IS DISTINCT FROM (NEW."update_interval"))',
                    declare='DECLARE child stac_api_Asset%ROWTYPE;',
                    func=
                    "\n-- update related item\nchild = COALESCE(NEW, OLD);\nUPDATE stac_api_item SET\n    etag = public.gen_random_uuid()\nWHERE id = child.item_id;\n\nRAISE INFO '%: updated item.id=% due to Asset.id=%',\n    TG_NAME, child.item_id, child.id;\n\nRETURN child;\n",
                    hash='0fe0c105ae381f2286b0e884cf7f92040f7d07fa',
                    operation='UPDATE',
                    pgid='pgtrigger_update_item_child_trigger_etag_only_03b47',
                    table='stac_api_asset',
                    when='AFTER'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='collection',
            trigger=pgtrigger.compiler.Trigger(
                name='add_collection_auto_variables_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func=
                    "NEW.etag = gen_random_uuid();NEW.updated = now();\n            RAISE INFO '%: updated % where id=%', TG_NAME, TG_TABLE_NAME, NEW.id;\n            RETURN NEW;\n",
                    hash='06e7b5a1b8d60aa0b5c99b62c8354d174638becd',
                    operation='INSERT',
                    pgid='pgtrigger_add_collection_auto_variables_trigger_c2d7a',
                    table='stac_api_collection',
                    when='BEFORE'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='collection',
            trigger=pgtrigger.compiler.Trigger(
                name='update_collection_etag_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)',
                    func=
                    "NEW.etag = gen_random_uuid();\n            RAISE INFO '%: updated % where id=%', TG_NAME, TG_TABLE_NAME, NEW.id;\n            RETURN NEW;\n",
                    hash='d30a2627a8fc31422740b803e91e1524873e2560',
                    operation='UPDATE',
                    pgid='pgtrigger_update_collection_etag_trigger_e0f93',
                    table='stac_api_collection',
                    when='BEFORE'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='collectionasset',
            trigger=pgtrigger.compiler.Trigger(
                name='add_col_asset_auto_variables_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func=
                    "NEW.etag = gen_random_uuid();NEW.updated = now();\n            RAISE INFO '%: updated % where id=%', TG_NAME, TG_TABLE_NAME, NEW.id;\n            RETURN NEW;\n",
                    hash='7c3d3c330c070407588922c1ab982ee14b08a42b',
                    operation='INSERT',
                    pgid='pgtrigger_add_col_asset_auto_variables_trigger_1ff98',
                    table='stac_api_collectionasset',
                    when='BEFORE'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='collectionasset',
            trigger=pgtrigger.compiler.Trigger(
                name='update_col_asset_etag_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)',
                    func=
                    "NEW.etag = gen_random_uuid();\n            RAISE INFO '%: updated % where id=%', TG_NAME, TG_TABLE_NAME, NEW.id;\n            RETURN NEW;\n",
                    hash='91afb48b71adbff0287bb0dd6847823fc82b5afc',
                    operation='UPDATE',
                    pgid='pgtrigger_update_col_asset_etag_trigger_662ff',
                    table='stac_api_collectionasset',
                    when='BEFORE'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='collectionasset',
            trigger=pgtrigger.compiler.Trigger(
                name='update_col_asset_timestamp_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition=
                    'WHEN (OLD."checksum_multihash" IS DISTINCT FROM (NEW."checksum_multihash") OR OLD."file" IS DISTINCT FROM (NEW."file"))',
                    func=
                    "NEW.updated = now();\n            RAISE INFO '%: updated % where id=%', TG_NAME, TG_TABLE_NAME, NEW.id;\n            RETURN NEW;\n",
                    hash='5c0045e88663bbbf7c87563d04fd7d7e548c2663',
                    operation='UPDATE',
                    pgid='pgtrigger_update_col_asset_timestamp_trigger_5bcc9',
                    table='stac_api_collectionasset',
                    when='BEFORE'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='collectionasset',
            trigger=pgtrigger.compiler.Trigger(
                name='add_or_del_collection_child_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    declare='DECLARE child stac_api_CollectionAsset%ROWTYPE;',
                    func=
                    "\n-- update related collection\nchild = COALESCE(NEW, OLD);\nUPDATE stac_api_collection SET\n    etag = public.gen_random_uuid(), updated = now()\nWHERE id = child.collection_id;\n\nRAISE INFO '%: updated collection.id=% due to CollectionAsset.id=%',\n    TG_NAME, child.collection_id, child.id;\n\nRETURN child;\n",
                    hash='ce46b9ca67568968003981849fcf4301d644cd45',
                    operation='INSERT OR DELETE',
                    pgid='pgtrigger_add_or_del_collection_child_trigger_5e28a',
                    table='stac_api_collectionasset',
                    when='AFTER'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='collectionasset',
            trigger=pgtrigger.compiler.Trigger(
                name='update_collection_child_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."updated" IS DISTINCT FROM (NEW."updated"))',
                    declare='DECLARE child stac_api_CollectionAsset%ROWTYPE;',
                    func=
                    "\n-- update related collection\nchild = COALESCE(NEW, OLD);\nUPDATE stac_api_collection SET\n    etag = public.gen_random_uuid(), updated = now()\nWHERE id = child.collection_id;\n\nRAISE INFO '%: updated collection.id=% due to CollectionAsset.id=%',\n    TG_NAME, child.collection_id, child.id;\n\nRETURN child;\n",
                    hash='8abac3ea4610f9bb4f6e752dcbfe9801ba22f43b',
                    operation='UPDATE',
                    pgid='pgtrigger_update_collection_child_trigger_ae85d',
                    table='stac_api_collectionasset',
                    when='AFTER'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='collectionasset',
            trigger=pgtrigger.compiler.Trigger(
                name='update_collection_child_trigger_etag_only',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition=
                    'WHEN (OLD."checksum_multihash" IS DISTINCT FROM (NEW."checksum_multihash") OR OLD."collection_id" IS DISTINCT FROM (NEW."collection_id") OR OLD."created" IS DISTINCT FROM (NEW."created") OR OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."etag" IS DISTINCT FROM (NEW."etag") OR OLD."file" IS DISTINCT FROM (NEW."file") OR OLD."file_size" IS DISTINCT FROM (NEW."file_size") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."is_external" IS DISTINCT FROM (NEW."is_external") OR OLD."media_type" IS DISTINCT FROM (NEW."media_type") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."proj_epsg" IS DISTINCT FROM (NEW."proj_epsg") OR OLD."roles" IS DISTINCT FROM (NEW."roles") OR OLD."title" IS DISTINCT FROM (NEW."title") OR OLD."update_interval" IS DISTINCT FROM (NEW."update_interval"))',
                    declare='DECLARE child stac_api_CollectionAsset%ROWTYPE;',
                    func=
                    "\n-- update related collection\nchild = COALESCE(NEW, OLD);\nUPDATE stac_api_collection SET\n    etag = public.gen_random_uuid()\nWHERE id = child.collection_id;\n\nRAISE INFO '%: updated collection.id=% due to CollectionAsset.id=%',\n    TG_NAME, child.collection_id, child.id;\n\nRETURN child;\n",
                    hash='04d7249836496799a633ffe1b7412166cdf82fcb',
                    operation='UPDATE',
                    pgid='pgtrigger_update_collection_child_trigger_etag_only_39619',
                    table='stac_api_collectionasset',
                    when='AFTER'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='collectionlink',
            trigger=pgtrigger.compiler.Trigger(
                name='add_or_del_collection_child_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    declare='DECLARE child stac_api_CollectionLink%ROWTYPE;',
                    func=
                    "\n-- update related collection\nchild = COALESCE(NEW, OLD);\nUPDATE stac_api_collection SET\n    etag = public.gen_random_uuid(), updated = now()\nWHERE id = child.collection_id;\n\nRAISE INFO '%: updated collection.id=% due to CollectionLink.id=%',\n    TG_NAME, child.collection_id, child.id;\n\nRETURN child;\n",
                    hash='2747572b80a26a627a8836ab139f70d49d191e88',
                    operation='INSERT OR DELETE',
                    pgid='pgtrigger_add_or_del_collection_child_trigger_df2ed',
                    table='stac_api_collectionlink',
                    when='AFTER'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='collectionlink',
            trigger=pgtrigger.compiler.Trigger(
                name='update_collection_child_trigger_etag_only',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)',
                    declare='DECLARE child stac_api_CollectionLink%ROWTYPE;',
                    func=
                    "\n-- update related collection\nchild = COALESCE(NEW, OLD);\nUPDATE stac_api_collection SET\n    etag = public.gen_random_uuid()\nWHERE id = child.collection_id;\n\nRAISE INFO '%: updated collection.id=% due to CollectionLink.id=%',\n    TG_NAME, child.collection_id, child.id;\n\nRETURN child;\n",
                    hash='2613c4cf4a32c6d4a1cca27e12a5e4c6fee636fa',
                    operation='UPDATE',
                    pgid='pgtrigger_update_collection_child_trigger_etag_only_abc6f',
                    table='stac_api_collectionlink',
                    when='AFTER'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='item',
            trigger=pgtrigger.compiler.Trigger(
                name='add_item_auto_variables_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func=
                    "NEW.etag = gen_random_uuid();NEW.updated = now();\n            RAISE INFO '%: updated % where id=%', TG_NAME, TG_TABLE_NAME, NEW.id;\n            RETURN NEW;\n",
                    hash='535fcdf31389f360ff1ec8792b40b877a39c00e4',
                    operation='INSERT',
                    pgid='pgtrigger_add_item_auto_variables_trigger_09b8c',
                    table='stac_api_item',
                    when='BEFORE'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='item',
            trigger=pgtrigger.compiler.Trigger(
                name='update_item_etag_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)',
                    func=
                    "NEW.etag = gen_random_uuid();\n            RAISE INFO '%: updated % where id=%', TG_NAME, TG_TABLE_NAME, NEW.id;\n            RETURN NEW;\n",
                    hash='4fa66e3f2c7100582be3e326512baf0d2ca7b655',
                    operation='UPDATE',
                    pgid='pgtrigger_update_item_etag_trigger_ce016',
                    table='stac_api_item',
                    when='BEFORE'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='item',
            trigger=pgtrigger.compiler.Trigger(
                name='add_or_del_collection_child_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    declare='DECLARE child stac_api_Item%ROWTYPE;',
                    func=
                    "\n-- update related collection\nchild = COALESCE(NEW, OLD);\nUPDATE stac_api_collection SET\n    etag = public.gen_random_uuid(), updated = now()\nWHERE id = child.collection_id;\n\nRAISE INFO '%: updated collection.id=% due to Item.id=%',\n    TG_NAME, child.collection_id, child.id;\n\nRETURN child;\n",
                    hash='06ee42e5f0fcaaa3acb9a6c31471b5924d880c59',
                    operation='INSERT OR DELETE',
                    pgid='pgtrigger_add_or_del_collection_child_trigger_bbfb9',
                    table='stac_api_item',
                    when='AFTER'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='item',
            trigger=pgtrigger.compiler.Trigger(
                name='update_collection_child_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."updated" IS DISTINCT FROM (NEW."updated"))',
                    declare='DECLARE child stac_api_Item%ROWTYPE;',
                    func=
                    "\n-- update related collection\nchild = COALESCE(NEW, OLD);\nUPDATE stac_api_collection SET\n    etag = public.gen_random_uuid(), updated = now()\nWHERE id = child.collection_id;\n\nRAISE INFO '%: updated collection.id=% due to Item.id=%',\n    TG_NAME, child.collection_id, child.id;\n\nRETURN child;\n",
                    hash='18293ffce77f2f2968fbe7b5fd6f96b4343f72ed',
                    operation='UPDATE',
                    pgid='pgtrigger_update_collection_child_trigger_c0533',
                    table='stac_api_item',
                    when='AFTER'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='item',
            trigger=pgtrigger.compiler.Trigger(
                name='update_collection_child_trigger_etag_only',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition=
                    'WHEN (OLD."collection_id" IS DISTINCT FROM (NEW."collection_id") OR OLD."created" IS DISTINCT FROM (NEW."created") OR OLD."etag" IS DISTINCT FROM (NEW."etag") OR OLD."forecast_duration" IS DISTINCT FROM (NEW."forecast_duration") OR OLD."forecast_horizon" IS DISTINCT FROM (NEW."forecast_horizon") OR OLD."forecast_perturbed" IS DISTINCT FROM (NEW."forecast_perturbed") OR OLD."forecast_reference_datetime" IS DISTINCT FROM (NEW."forecast_reference_datetime") OR OLD."forecast_variable" IS DISTINCT FROM (NEW."forecast_variable") OR OLD."geometry" IS DISTINCT FROM (NEW."geometry") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."properties_datetime" IS DISTINCT FROM (NEW."properties_datetime") OR OLD."properties_end_datetime" IS DISTINCT FROM (NEW."properties_end_datetime") OR OLD."properties_expires" IS DISTINCT FROM (NEW."properties_expires") OR OLD."properties_start_datetime" IS DISTINCT FROM (NEW."properties_start_datetime") OR OLD."properties_title" IS DISTINCT FROM (NEW."properties_title") OR OLD."total_data_size" IS DISTINCT FROM (NEW."total_data_size"))',
                    declare='DECLARE child stac_api_Item%ROWTYPE;',
                    func=
                    "\n-- update related collection\nchild = COALESCE(NEW, OLD);\nUPDATE stac_api_collection SET\n    etag = public.gen_random_uuid()\nWHERE id = child.collection_id;\n\nRAISE INFO '%: updated collection.id=% due to Item.id=%',\n    TG_NAME, child.collection_id, child.id;\n\nRETURN child;\n",
                    hash='cf85eadf1f537c62a029fb3ee528ac3e95b8678e',
                    operation='UPDATE',
                    pgid='pgtrigger_update_collection_child_trigger_etag_only_bee6a',
                    table='stac_api_item',
                    when='AFTER'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='itemlink',
            trigger=pgtrigger.compiler.Trigger(
                name='add_or_del_item_child_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    declare='DECLARE child stac_api_ItemLink%ROWTYPE;',
                    func=
                    "\n-- update related item\nchild = COALESCE(NEW, OLD);\nUPDATE stac_api_item SET\n    etag = public.gen_random_uuid(), updated = now()\nWHERE id = child.item_id;\n\nRAISE INFO '%: updated item.id=% due to ItemLink.id=%',\n    TG_NAME, child.item_id, child.id;\n\nRETURN child;\n",
                    hash='5f8018336bd07d03f04579d9361ceb46412e06a0',
                    operation='INSERT OR DELETE',
                    pgid='pgtrigger_add_or_del_item_child_trigger_ed449',
                    table='stac_api_itemlink',
                    when='AFTER'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='itemlink',
            trigger=pgtrigger.compiler.Trigger(
                name='update_item_child_trigger_etag_only',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)',
                    declare='DECLARE child stac_api_ItemLink%ROWTYPE;',
                    func=
                    "\n-- update related item\nchild = COALESCE(NEW, OLD);\nUPDATE stac_api_item SET\n    etag = public.gen_random_uuid()\nWHERE id = child.item_id;\n\nRAISE INFO '%: updated item.id=% due to ItemLink.id=%',\n    TG_NAME, child.item_id, child.id;\n\nRETURN child;\n",
                    hash='bcdcd93fa0ddeac862ae79b29fcba60967608dca',
                    operation='UPDATE',
                    pgid='pgtrigger_update_item_child_trigger_etag_only_26a59',
                    table='stac_api_itemlink',
                    when='AFTER'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='provider',
            trigger=pgtrigger.compiler.Trigger(
                name='add_or_del_collection_child_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    declare='DECLARE child stac_api_Provider%ROWTYPE;',
                    func=
                    "\n-- update related collection\nchild = COALESCE(NEW, OLD);\nUPDATE stac_api_collection SET\n    etag = public.gen_random_uuid(), updated = now()\nWHERE id = child.collection_id;\n\nRAISE INFO '%: updated collection.id=% due to Provider.id=%',\n    TG_NAME, child.collection_id, child.id;\n\nRETURN child;\n",
                    hash='dbcf5b3f1c8e79410a77c8d4fa8c43219742ac6b',
                    operation='INSERT OR DELETE',
                    pgid='pgtrigger_add_or_del_collection_child_trigger_fed8c',
                    table='stac_api_provider',
                    when='AFTER'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='provider',
            trigger=pgtrigger.compiler.Trigger(
                name='update_collection_child_trigger_etag_only',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)',
                    declare='DECLARE child stac_api_Provider%ROWTYPE;',
                    func=
                    "\n-- update related collection\nchild = COALESCE(NEW, OLD);\nUPDATE stac_api_collection SET\n    etag = public.gen_random_uuid()\nWHERE id = child.collection_id;\n\nRAISE INFO '%: updated collection.id=% due to Provider.id=%',\n    TG_NAME, child.collection_id, child.id;\n\nRETURN child;\n",
                    hash='72edba27892009109b86e753f2e5049618f6e7fd',
                    operation='UPDATE',
                    pgid='pgtrigger_update_collection_child_trigger_etag_only_33a97',
                    table='stac_api_provider',
                    when='AFTER'
                )
            ),
        ),
    ]
