# Generated by Django 5.2.13 on 2026-07-15 16:43

import django.contrib.postgres.fields
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0077_remove_asset_add_asset_auto_variables_trigger_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='item',
            name='update_collection_child_trigger_etag_only',
        ),
        migrations.AddField(
            model_name='collection',
            name='stac_extensions_enabled',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('https://stac-extensions.github.io/timestamps/v1.1.0/schema.json', 'Timestamps'), ('https://stac-extensions.github.io/forecast/v0.2.0/schema.json', 'Forecast')], max_length=255), blank=True, default=list, help_text='STAC extensions that are enabled for the Items in this Collection. It defines which STAC extensions are allowed to be used by the Items in this Collection. This field is for internal/admin use only, it is not exposed through the STAC API.', size=None),
        ),
        migrations.AddField(
            model_name='item',
            name='stac_extensions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('https://stac-extensions.github.io/timestamps/v1.1.0/schema.json', 'Timestamps'), ('https://stac-extensions.github.io/forecast/v0.2.0/schema.json', 'Forecast')], max_length=255), blank=True, default=list, help_text="STAC extensions used by this Item. Defined as JSON schema URLs. Must be a subset of the Collection's stac_extensions_enabled field.", size=None),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='item',
            trigger=pgtrigger.compiler.Trigger(name='update_collection_child_trigger_etag_only', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."collection_id" IS DISTINCT FROM (NEW."collection_id") OR OLD."created" IS DISTINCT FROM (NEW."created") OR OLD."etag" IS DISTINCT FROM (NEW."etag") OR OLD."forecast_duration" IS DISTINCT FROM (NEW."forecast_duration") OR OLD."forecast_horizon" IS DISTINCT FROM (NEW."forecast_horizon") OR OLD."forecast_perturbed" IS DISTINCT FROM (NEW."forecast_perturbed") OR OLD."forecast_reference_datetime" IS DISTINCT FROM (NEW."forecast_reference_datetime") OR OLD."forecast_variable" IS DISTINCT FROM (NEW."forecast_variable") OR OLD."geometry" IS DISTINCT FROM (NEW."geometry") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."properties_datetime" IS DISTINCT FROM (NEW."properties_datetime") OR OLD."properties_end_datetime" IS DISTINCT FROM (NEW."properties_end_datetime") OR OLD."properties_expires" IS DISTINCT FROM (NEW."properties_expires") OR OLD."properties_start_datetime" IS DISTINCT FROM (NEW."properties_start_datetime") OR OLD."properties_title" IS DISTINCT FROM (NEW."properties_title") OR OLD."stac_extensions" IS DISTINCT FROM (NEW."stac_extensions") OR OLD."total_data_size" IS DISTINCT FROM (NEW."total_data_size"))', declare='DECLARE child stac_api_Item%ROWTYPE;', func="\n-- update related collection\nchild = COALESCE(NEW, OLD);\nUPDATE stac_api_collection SET\n    etag = public.gen_random_uuid()\nWHERE id = child.collection_id;\n\nRAISE INFO '%: updated collection.id=% due to Item.id=%',\n    TG_NAME, child.collection_id, child.id;\n\nRETURN child;\n", hash='44c9e53a63aa52973de9b729e17eca6a036d0018', operation='UPDATE', pgid='pgtrigger_update_collection_child_trigger_etag_only_bee6a', table='stac_api_item', when='AFTER')),
        ),
    ]
