# Generated by Django 5.2.13 on 2026-07-29 15:40

from django.db import migrations

from stac_api.validators import StacExtension

FORECAST_EXT = StacExtension.FORECAST.value
TIMESTAMPS_EXT = StacExtension.TIMESTAMPS.value


def update_stac_extensions(apps, schema_editor):
    """Add STAC extensions based on item properties.

    - Item with `forecast_reference_datetime` != 0:
        Add forecast extension to `stac_extension` and to the collection's
        `stac_extension_enabled`
    - Item with `properties_expires` != 0:
        Add timestamps extension to `stac_extension` and to the collection's
        `stac_extension_enabled`
    """
    Item = apps.get_model('stac_api', 'Item')

    forecast_collections_updated = set()
    timestamps_collections_updated = set()

    for item in Item.objects.filter(forecast_reference_datetime__isnull=False):
        extensions = list(item.stac_extensions)
        if FORECAST_EXT not in extensions:
            extensions.append(FORECAST_EXT)
            item.stac_extensions = extensions
            item.save()

        if item.collection_id not in forecast_collections_updated:
            collection = item.collection
            extensions = list(collection.stac_extensions_enabled)
            if FORECAST_EXT not in extensions:
                extensions.append(FORECAST_EXT)
                collection.stac_extensions_enabled = extensions
                collection.save()
            forecast_collections_updated.add(item.collection_id)

    for item in Item.objects.filter(properties_expires__isnull=False):
        extensions = list(item.stac_extensions)
        if TIMESTAMPS_EXT not in extensions:
            extensions.append(TIMESTAMPS_EXT)
            item.stac_extensions = extensions
            item.save()

        if item.collection_id not in timestamps_collections_updated:
            collection = item.collection
            extensions = list(collection.stac_extensions_enabled)
            if TIMESTAMPS_EXT not in extensions:
                extensions.append(TIMESTAMPS_EXT)
                collection.stac_extensions_enabled = extensions
                collection.save()
            timestamps_collections_updated.add(item.collection_id)


def reverse_update_stac_extensions(apps, schema_editor):
    """Remove STAC extensions added by this migration."""
    Item = apps.get_model('stac_api', 'Item')

    forecast_collections_updated = set()
    timestamps_collections_updated = set()

    for item in Item.objects.filter(forecast_reference_datetime__isnull=False):
        item.stac_extensions = [ext for ext in item.stac_extensions if ext != FORECAST_EXT]
        item.save()

        if item.collection_id not in forecast_collections_updated:
            collection = item.collection
            collection.stac_extensions_enabled = [
                ext for ext in collection.stac_extensions_enabled if ext != FORECAST_EXT
            ]
            collection.save()
            forecast_collections_updated.add(item.collection_id)

    for item in Item.objects.filter(properties_expires__isnull=False):
        item.stac_extensions = [ext for ext in item.stac_extensions if ext != TIMESTAMPS_EXT]
        item.save()

        if item.collection_id not in timestamps_collections_updated:
            collection = item.collection
            collection.stac_extensions_enabled = [
                ext for ext in collection.stac_extensions_enabled if ext != TIMESTAMPS_EXT
            ]
            collection.save()
            timestamps_collections_updated.add(item.collection_id)


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0078_remove_item_update_collection_child_trigger_etag_only_and_more'),
    ]

    operations = [
        migrations.RunPython(
            update_stac_extensions,
            reverse_update_stac_extensions,
        ),
    ]
