# Generated by Django 5.2.13 on 2026-08-10 16:43

import pgtrigger.compiler
import pgtrigger.migrations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0079_add_stac_extensions_to_meteoschweiz_collections'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cf_standard_name',
            field=models.CharField(
                blank=True,
                help_text='Corresponds to the CF Standard Name from the CF Standard Name Table.',
                max_length=255,
                null=True
            ),
        ),
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.CharField(
                blank=True, help_text='Corresponds to the CF units.', max_length=255, null=True
            ),
        ),
    ]
