# Generated by Django 5.2.13 on 2026-08-11 15:15

import pgtrigger.compiler
import pgtrigger.migrations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0080_item_cf_standard_name_item_unit'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='item',
            name='update_collection_child_trigger_etag_only',
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['cf_standard_name'], name='item_cf_standard_name_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['unit'], name='item_unit_idx'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='item',
            trigger=pgtrigger.compiler.Trigger(
                name='update_collection_child_trigger_etag_only',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition=
                    'WHEN (OLD."cf_standard_name" IS DISTINCT FROM (NEW."cf_standard_name") OR OLD."collection_id" IS DISTINCT FROM (NEW."collection_id") OR OLD."created" IS DISTINCT FROM (NEW."created") OR OLD."etag" IS DISTINCT FROM (NEW."etag") OR OLD."forecast_duration" IS DISTINCT FROM (NEW."forecast_duration") OR OLD."forecast_horizon" IS DISTINCT FROM (NEW."forecast_horizon") OR OLD."forecast_perturbed" IS DISTINCT FROM (NEW."forecast_perturbed") OR OLD."forecast_reference_datetime" IS DISTINCT FROM (NEW."forecast_reference_datetime") OR OLD."forecast_variable" IS DISTINCT FROM (NEW."forecast_variable") OR OLD."geometry" IS DISTINCT FROM (NEW."geometry") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."properties_datetime" IS DISTINCT FROM (NEW."properties_datetime") OR OLD."properties_end_datetime" IS DISTINCT FROM (NEW."properties_end_datetime") OR OLD."properties_expires" IS DISTINCT FROM (NEW."properties_expires") OR OLD."properties_start_datetime" IS DISTINCT FROM (NEW."properties_start_datetime") OR OLD."properties_title" IS DISTINCT FROM (NEW."properties_title") OR OLD."stac_extensions" IS DISTINCT FROM (NEW."stac_extensions") OR OLD."total_data_size" IS DISTINCT FROM (NEW."total_data_size") OR OLD."unit" IS DISTINCT FROM (NEW."unit"))',
                    declare='DECLARE child stac_api_Item%ROWTYPE;',
                    func=
                    "\n-- update related collection\nchild = COALESCE(NEW, OLD);\nUPDATE stac_api_collection SET\n    etag = public.gen_random_uuid()\nWHERE id = child.collection_id;\n\nRAISE INFO '%: updated collection.id=% due to Item.id=%',\n    TG_NAME, child.collection_id, child.id;\n\nRETURN child;\n",
                    hash='0308e4b3217a2be3890fde8659088ee924d8c59a',
                    operation='UPDATE',
                    pgid='pgtrigger_update_collection_child_trigger_etag_only_bee6a',
                    table='stac_api_item',
                    when='AFTER'
                )
            ),
        ),
    ]
