# Generated by Django 5.2.13 on 2026-08-11 17:03

import django.contrib.postgres.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0081_remove_item_update_collection_child_trigger_etag_only_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='stac_extensions_enabled',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[(
                        'https://stac-extensions.github.io/timestamps/v1.1.0/schema.json',
                        'Timestamps'
                    ),
                             (
                                 'https://stac-extensions.github.io/forecast/v0.2.0/schema.json',
                                 'Forecast'
                             ), ('https://stac-extensions.github.io/cf/v1.0.0/schema.json', 'CF')],
                    max_length=255
                ),
                blank=True,
                default=list,
                help_text=
                'STAC extensions that are enabled for the Items in this Collection. It defines which STAC extensions are allowed to be used by the Items in this Collection. This field is for internal/admin use only, it is not exposed through the STAC API.',
                size=None
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='stac_extensions',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[(
                        'https://stac-extensions.github.io/timestamps/v1.1.0/schema.json',
                        'Timestamps'
                    ),
                             (
                                 'https://stac-extensions.github.io/forecast/v0.2.0/schema.json',
                                 'Forecast'
                             ), ('https://stac-extensions.github.io/cf/v1.0.0/schema.json', 'CF')],
                    max_length=255
                ),
                blank=True,
                default=list,
                help_text=
                "STAC extensions used by this Item. Defined as JSON schema URLs. Must be a subset of the Collection's stac_extensions_enabled field.",
                size=None
            ),
        ),
    ]
