# Generated by Django 5.2.13 on 2026-10-08 11:46

import pgtrigger.compiler
import pgtrigger.migrations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stac_api', '0083_add_sort_conformance_classes'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='asset',
            name='upd_dec_eo_gsd_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='asset',
            name='del_eo_gsd_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='asset',
            name='upd_inc_eo_gsd_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='asset',
            name='add_eo_gsd_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='asset',
            name='upd_dec_geoadmin_lang_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='asset',
            name='del_geoadmin_lang_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='asset',
            name='upd_inc_geoadmin_lang_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='asset',
            name='add_geoadmin_lang_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='asset',
            name='upd_dec_geoadmin_variant_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='asset',
            name='del_geoadmin_variant_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='asset',
            name='upd_inc_geoadmin_variant_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='asset',
            name='add_geoadmin_variant_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='asset',
            name='upd_dec_proj_epsg_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='asset',
            name='del_proj_epsg_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='asset',
            name='upd_inc_proj_epsg_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='asset',
            name='add_proj_epsg_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='collectionasset',
            name='del_col_asset_proj_epsg_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='collectionasset',
            name='add_col_asset_proj_epsg_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='collectionasset',
            name='upd_dec_col_asset_proj_epsg_trigger',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='collectionasset',
            name='upd_inc_col_asset_proj_epsg_trigger',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='asset',
            trigger=pgtrigger.compiler.Trigger(
                name='upd_dec_eo_gsd_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD.eo_gsd IS DISTINCT FROM NEW.eo_gsd)',
                    declare=
                    'DECLARE asset_instance stac_api_asset%ROWTYPE; related_collection_id INT;',
                    func=
                    "\n        asset_instance = OLD;\n\n        -- NULL values are not part of the summaries and are not counted\n        IF asset_instance.eo_gsd IS NULL THEN\n            RETURN asset_instance;\n        END IF;\n\n        related_collection_id = (\n            SELECT collection_id FROM stac_api_item\n            WHERE id = asset_instance.item_id\n        );\n\n        -- Remove entry when count will reach 0\n        DELETE FROM stac_api_gsdcount\n        WHERE collection_id = related_collection_id\n            AND value = asset_instance.eo_gsd\n            AND count = 1;\n\n        IF NOT FOUND THEN\n        UPDATE stac_api_gsdcount\n        SET count = count-1\n        WHERE collection_id = related_collection_id\n            AND value = asset_instance.eo_gsd;\n\n        RAISE INFO\n            'gsdcount (collection_id, value) (% %) count updated, due to asset.name=% update.',\n            related_collection_id, asset_instance.eo_gsd, asset_instance.name;\n\n        RETURN asset_instance;\n        END IF;\n\n        RAISE INFO\n            'gsdcount (collection_id, value) (% %) deleted, due to asset.name=% update.',\n            related_collection_id, asset_instance.eo_gsd, asset_instance.name;\n\n        RETURN asset_instance;\n        ",
                    hash='e66cb16fd84e1fea8f5c2646442b975d8dad1f7a',
                    operation='UPDATE',
                    pgid='pgtrigger_upd_dec_eo_gsd_trigger_3d90f',
                    table='stac_api_asset',
                    when='AFTER'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='asset',
            trigger=pgtrigger.compiler.Trigger(
                name='del_eo_gsd_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    declare=
                    'DECLARE asset_instance stac_api_asset%ROWTYPE; related_collection_id INT;',
                    func=
                    "\n        asset_instance = OLD;\n\n        -- NULL values are not part of the summaries and are not counted\n        IF asset_instance.eo_gsd IS NULL THEN\n            RETURN asset_instance;\n        END IF;\n\n        related_collection_id = (\n            SELECT collection_id FROM stac_api_item\n            WHERE id = asset_instance.item_id\n        );\n\n        -- Remove entry when count will reach 0\n        DELETE FROM stac_api_gsdcount\n        WHERE collection_id = related_collection_id\n            AND value = asset_instance.eo_gsd\n            AND count = 1;\n\n        IF NOT FOUND THEN\n        UPDATE stac_api_gsdcount\n        SET count = count-1\n        WHERE collection_id = related_collection_id\n            AND value = asset_instance.eo_gsd;\n\n        RAISE INFO\n            'gsdcount (collection_id, value) (% %) count updated, due to asset.name=% update.',\n            related_collection_id, asset_instance.eo_gsd, asset_instance.name;\n\n        RETURN asset_instance;\n        END IF;\n\n        RAISE INFO\n            'gsdcount (collection_id, value) (% %) deleted, due to asset.name=% update.',\n            related_collection_id, asset_instance.eo_gsd, asset_instance.name;\n\n        RETURN asset_instance;\n        ",
                    hash='c59e0fa6a6f4d479a88d099ab4357508e273c9a1',
                    operation='DELETE',
                    pgid='pgtrigger_del_eo_gsd_trigger_ccfab',
                    table='stac_api_asset',
                    when='AFTER'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='asset',
            trigger=pgtrigger.compiler.Trigger(
                name='upd_inc_eo_gsd_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD.eo_gsd IS DISTINCT FROM NEW.eo_gsd)',
                    declare=
                    'DECLARE asset_instance stac_api_asset%ROWTYPE; related_collection_id INT;',
                    func=
                    "\n        asset_instance = NEW;\n\n        -- NULL values are not part of the summaries and are not counted\n        IF asset_instance.eo_gsd IS NULL THEN\n            RETURN asset_instance;\n        END IF;\n\n        related_collection_id = (\n            SELECT collection_id FROM stac_api_item\n            WHERE id = asset_instance.item_id\n        );\n\n        INSERT INTO stac_api_gsdcount (collection_id, value, count)\n        VALUES (related_collection_id, asset_instance.eo_gsd, 1)\n        ON CONFLICT (collection_id, value)\n        DO UPDATE SET count = stac_api_gsdcount.count+1;\n\n        RAISE INFO\n            'gsdcount (collection_id, value) (% %) count updated, due to asset.name=% update.',\n            related_collection_id, asset_instance.eo_gsd, asset_instance.name;\n\n        RETURN asset_instance;\n        ",
                    hash='bf86d6640ae7480712ca7ed8bd4f4968098f85a8',
                    operation='UPDATE',
                    pgid='pgtrigger_upd_inc_eo_gsd_trigger_b0c4f',
                    table='stac_api_asset',
                    when='AFTER'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='asset',
            trigger=pgtrigger.compiler.Trigger(
                name='add_eo_gsd_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    declare=
                    'DECLARE asset_instance stac_api_asset%ROWTYPE; related_collection_id INT;',
                    func=
                    "\n        asset_instance = NEW;\n\n        -- NULL values are not part of the summaries and are not counted\n        IF asset_instance.eo_gsd IS NULL THEN\n            RETURN asset_instance;\n        END IF;\n\n        related_collection_id = (\n            SELECT collection_id FROM stac_api_item\n            WHERE id = asset_instance.item_id\n        );\n\n        INSERT INTO stac_api_gsdcount (collection_id, value, count)\n        VALUES (related_collection_id, asset_instance.eo_gsd, 1)\n        ON CONFLICT (collection_id, value)\n        DO UPDATE SET count = stac_api_gsdcount.count+1;\n\n        RAISE INFO\n            'gsdcount (collection_id, value) (% %) count updated, due to asset.name=% update.',\n            related_collection_id, asset_instance.eo_gsd, asset_instance.name;\n\n        RETURN asset_instance;\n        ",
                    hash='8b408854f6ed3b084476c311655bbebf593d720f',
                    operation='INSERT',
                    pgid='pgtrigger_add_eo_gsd_trigger_1edd9',
                    table='stac_api_asset',
                    when='AFTER'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='asset',
            trigger=pgtrigger.compiler.Trigger(
                name='upd_dec_geoadmin_lang_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD.geoadmin_lang IS DISTINCT FROM NEW.geoadmin_lang)',
                    declare=
                    'DECLARE asset_instance stac_api_asset%ROWTYPE; related_collection_id INT;',
                    func=
                    "\n        asset_instance = OLD;\n\n        -- NULL values are not part of the summaries and are not counted\n        IF asset_instance.geoadmin_lang IS NULL THEN\n            RETURN asset_instance;\n        END IF;\n\n        related_collection_id = (\n            SELECT collection_id FROM stac_api_item\n            WHERE id = asset_instance.item_id\n        );\n\n        -- Remove entry when count will reach 0\n        DELETE FROM stac_api_geoadminlangcount\n        WHERE collection_id = related_collection_id\n            AND value = asset_instance.geoadmin_lang\n            AND count = 1;\n\n        IF NOT FOUND THEN\n        UPDATE stac_api_geoadminlangcount\n        SET count = count-1\n        WHERE collection_id = related_collection_id\n            AND value = asset_instance.geoadmin_lang;\n\n        RAISE INFO\n            'geoadminlangcount (collection_id, value) (% %) count updated, due to asset.name=% update.',\n            related_collection_id, asset_instance.geoadmin_lang, asset_instance.name;\n\n        RETURN asset_instance;\n        END IF;\n\n        RAISE INFO\n            'geoadminlangcount (collection_id, value) (% %) deleted, due to asset.name=% update.',\n            related_collection_id, asset_instance.geoadmin_lang, asset_instance.name;\n\n        RETURN asset_instance;\n        ",
                    hash='28fa62c73f8eb6f44213c0077c7c0737a3eee482',
                    operation='UPDATE',
                    pgid='pgtrigger_upd_dec_geoadmin_lang_trigger_81453',
                    table='stac_api_asset',
                    when='AFTER'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='asset',
            trigger=pgtrigger.compiler.Trigger(
                name='del_geoadmin_lang_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    declare=
                    'DECLARE asset_instance stac_api_asset%ROWTYPE; related_collection_id INT;',
                    func=
                    "\n        asset_instance = OLD;\n\n        -- NULL values are not part of the summaries and are not counted\n        IF asset_instance.geoadmin_lang IS NULL THEN\n            RETURN asset_instance;\n        END IF;\n\n        related_collection_id = (\n            SELECT collection_id FROM stac_api_item\n            WHERE id = asset_instance.item_id\n        );\n\n        -- Remove entry when count will reach 0\n        DELETE FROM stac_api_geoadminlangcount\n        WHERE collection_id = related_collection_id\n            AND value = asset_instance.geoadmin_lang\n            AND count = 1;\n\n        IF NOT FOUND THEN\n        UPDATE stac_api_geoadminlangcount\n        SET count = count-1\n        WHERE collection_id = related_collection_id\n            AND value = asset_instance.geoadmin_lang;\n\n        RAISE INFO\n            'geoadminlangcount (collection_id, value) (% %) count updated, due to asset.name=% update.',\n            related_collection_id, asset_instance.geoadmin_lang, asset_instance.name;\n\n        RETURN asset_instance;\n        END IF;\n\n        RAISE INFO\n            'geoadminlangcount (collection_id, value) (% %) deleted, due to asset.name=% update.',\n            related_collection_id, asset_instance.geoadmin_lang, asset_instance.name;\n\n        RETURN asset_instance;\n        ",
                    hash='6576438017d440408f6b21287fce2820f01256cc',
                    operation='DELETE',
                    pgid='pgtrigger_del_geoadmin_lang_trigger_ad861',
                    table='stac_api_asset',
                    when='AFTER'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='asset',
            trigger=pgtrigger.compiler.Trigger(
                name='upd_inc_geoadmin_lang_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD.geoadmin_lang IS DISTINCT FROM NEW.geoadmin_lang)',
                    declare=
                    'DECLARE asset_instance stac_api_asset%ROWTYPE; related_collection_id INT;',
                    func=
                    "\n        asset_instance = NEW;\n\n        -- NULL values are not part of the summaries and are not counted\n        IF asset_instance.geoadmin_lang IS NULL THEN\n            RETURN asset_instance;\n        END IF;\n\n        related_collection_id = (\n            SELECT collection_id FROM stac_api_item\n            WHERE id = asset_instance.item_id\n        );\n\n        INSERT INTO stac_api_geoadminlangcount (collection_id, value, count)\n        VALUES (related_collection_id, asset_instance.geoadmin_lang, 1)\n        ON CONFLICT (collection_id, value)\n        DO UPDATE SET count = stac_api_geoadminlangcount.count+1;\n\n        RAISE INFO\n            'geoadminlangcount (collection_id, value) (% %) count updated, due to asset.name=% update.',\n            related_collection_id, asset_instance.geoadmin_lang, asset_instance.name;\n\n        RETURN asset_instance;\n        ",
                    hash='ae8976f56a277f8a91d00a73bee29c46d32bc2a8',
                    operation='UPDATE',
                    pgid='pgtrigger_upd_inc_geoadmin_lang_trigger_9db4d',
                    table='stac_api_asset',
                    when='AFTER'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='asset',
            trigger=pgtrigger.compiler.Trigger(
                name='add_geoadmin_lang_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    declare=
                    'DECLARE asset_instance stac_api_asset%ROWTYPE; related_collection_id INT;',
                    func=
                    "\n        asset_instance = NEW;\n\n        -- NULL values are not part of the summaries and are not counted\n        IF asset_instance.geoadmin_lang IS NULL THEN\n            RETURN asset_instance;\n        END IF;\n\n        related_collection_id = (\n            SELECT collection_id FROM stac_api_item\n            WHERE id = asset_instance.item_id\n        );\n\n        INSERT INTO stac_api_geoadminlangcount (collection_id, value, count)\n        VALUES (related_collection_id, asset_instance.geoadmin_lang, 1)\n        ON CONFLICT (collection_id, value)\n        DO UPDATE SET count = stac_api_geoadminlangcount.count+1;\n\n        RAISE INFO\n            'geoadminlangcount (collection_id, value) (% %) count updated, due to asset.name=% update.',\n            related_collection_id, asset_instance.geoadmin_lang, asset_instance.name;\n\n        RETURN asset_instance;\n        ",
                    hash='f9221c59d81a61ecbb49ab868b820c6600320325',
                    operation='INSERT',
                    pgid='pgtrigger_add_geoadmin_lang_trigger_b3618',
                    table='stac_api_asset',
                    when='AFTER'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='asset',
            trigger=pgtrigger.compiler.Trigger(
                name='upd_dec_geoadmin_variant_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD.geoadmin_variant IS DISTINCT FROM NEW.geoadmin_variant)',
                    declare=
                    'DECLARE asset_instance stac_api_asset%ROWTYPE; related_collection_id INT;',
                    func=
                    "\n        asset_instance = OLD;\n\n        -- NULL values are not part of the summaries and are not counted\n        IF asset_instance.geoadmin_variant IS NULL THEN\n            RETURN asset_instance;\n        END IF;\n\n        related_collection_id = (\n            SELECT collection_id FROM stac_api_item\n            WHERE id = asset_instance.item_id\n        );\n\n        -- Remove entry when count will reach 0\n        DELETE FROM stac_api_geoadminvariantcount\n        WHERE collection_id = related_collection_id\n            AND value = asset_instance.geoadmin_variant\n            AND count = 1;\n\n        IF NOT FOUND THEN\n        UPDATE stac_api_geoadminvariantcount\n        SET count = count-1\n        WHERE collection_id = related_collection_id\n            AND value = asset_instance.geoadmin_variant;\n\n        RAISE INFO\n            'geoadminvariantcount (collection_id, value) (% %) count updated, due to asset.name=% update.',\n            related_collection_id, asset_instance.geoadmin_variant, asset_instance.name;\n\n        RETURN asset_instance;\n        END IF;\n\n        RAISE INFO\n            'geoadminvariantcount (collection_id, value) (% %) deleted, due to asset.name=% update.',\n            related_collection_id, asset_instance.geoadmin_variant, asset_instance.name;\n\n        RETURN asset_instance;\n        ",
                    hash='4af275158729fe7f8cdef573b43f782cf72113e5',
                    operation='UPDATE',
                    pgid='pgtrigger_upd_dec_geoadmin_variant_trigger_27787',
                    table='stac_api_asset',
                    when='AFTER'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='asset',
            trigger=pgtrigger.compiler.Trigger(
                name='del_geoadmin_variant_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    declare=
                    'DECLARE asset_instance stac_api_asset%ROWTYPE; related_collection_id INT;',
                    func=
                    "\n        asset_instance = OLD;\n\n        -- NULL values are not part of the summaries and are not counted\n        IF asset_instance.geoadmin_variant IS NULL THEN\n            RETURN asset_instance;\n        END IF;\n\n        related_collection_id = (\n            SELECT collection_id FROM stac_api_item\n            WHERE id = asset_instance.item_id\n        );\n\n        -- Remove entry when count will reach 0\n        DELETE FROM stac_api_geoadminvariantcount\n        WHERE collection_id = related_collection_id\n            AND value = asset_instance.geoadmin_variant\n            AND count = 1;\n\n        IF NOT FOUND THEN\n        UPDATE stac_api_geoadminvariantcount\n        SET count = count-1\n        WHERE collection_id = related_collection_id\n            AND value = asset_instance.geoadmin_variant;\n\n        RAISE INFO\n            'geoadminvariantcount (collection_id, value) (% %) count updated, due to asset.name=% update.',\n            related_collection_id, asset_instance.geoadmin_variant, asset_instance.name;\n\n        RETURN asset_instance;\n        END IF;\n\n        RAISE INFO\n            'geoadminvariantcount (collection_id, value) (% %) deleted, due to asset.name=% update.',\n            related_collection_id, asset_instance.geoadmin_variant, asset_instance.name;\n\n        RETURN asset_instance;\n        ",
                    hash='4559abc7f91166a446c210e57c6d72f87daadf0f',
                    operation='DELETE',
                    pgid='pgtrigger_del_geoadmin_variant_trigger_154b3',
                    table='stac_api_asset',
                    when='AFTER'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='asset',
            trigger=pgtrigger.compiler.Trigger(
                name='upd_inc_geoadmin_variant_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD.geoadmin_variant IS DISTINCT FROM NEW.geoadmin_variant)',
                    declare=
                    'DECLARE asset_instance stac_api_asset%ROWTYPE; related_collection_id INT;',
                    func=
                    "\n        asset_instance = NEW;\n\n        -- NULL values are not part of the summaries and are not counted\n        IF asset_instance.geoadmin_variant IS NULL THEN\n            RETURN asset_instance;\n        END IF;\n\n        related_collection_id = (\n            SELECT collection_id FROM stac_api_item\n            WHERE id = asset_instance.item_id\n        );\n\n        INSERT INTO stac_api_geoadminvariantcount (collection_id, value, count)\n        VALUES (related_collection_id, asset_instance.geoadmin_variant, 1)\n        ON CONFLICT (collection_id, value)\n        DO UPDATE SET count = stac_api_geoadminvariantcount.count+1;\n\n        RAISE INFO\n            'geoadminvariantcount (collection_id, value) (% %) count updated, due to asset.name=% update.',\n            related_collection_id, asset_instance.geoadmin_variant, asset_instance.name;\n\n        RETURN asset_instance;\n        ",
                    hash='86c964b706a377d0fed9e8452ac9e2e4e1246b10',
                    operation='UPDATE',
                    pgid='pgtrigger_upd_inc_geoadmin_variant_trigger_cff3e',
                    table='stac_api_asset',
                    when='AFTER'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='asset',
            trigger=pgtrigger.compiler.Trigger(
                name='add_geoadmin_variant_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    declare=
                    'DECLARE asset_instance stac_api_asset%ROWTYPE; related_collection_id INT;',
                    func=
                    "\n        asset_instance = NEW;\n\n        -- NULL values are not part of the summaries and are not counted\n        IF asset_instance.geoadmin_variant IS NULL THEN\n            RETURN asset_instance;\n        END IF;\n\n        related_collection_id = (\n            SELECT collection_id FROM stac_api_item\n            WHERE id = asset_instance.item_id\n        );\n\n        INSERT INTO stac_api_geoadminvariantcount (collection_id, value, count)\n        VALUES (related_collection_id, asset_instance.geoadmin_variant, 1)\n        ON CONFLICT (collection_id, value)\n        DO UPDATE SET count = stac_api_geoadminvariantcount.count+1;\n\n        RAISE INFO\n            'geoadminvariantcount (collection_id, value) (% %) count updated, due to asset.name=% update.',\n            related_collection_id, asset_instance.geoadmin_variant, asset_instance.name;\n\n        RETURN asset_instance;\n        ",
                    hash='a423e86aa3a48cad2ab06e2ef80bb435246d1742',
                    operation='INSERT',
                    pgid='pgtrigger_add_geoadmin_variant_trigger_57810',
                    table='stac_api_asset',
                    when='AFTER'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='asset',
            trigger=pgtrigger.compiler.Trigger(
                name='upd_dec_proj_epsg_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD.proj_epsg IS DISTINCT FROM NEW.proj_epsg)',
                    declare=
                    'DECLARE asset_instance stac_api_asset%ROWTYPE; related_collection_id INT;',
                    func=
                    "\n        asset_instance = OLD;\n\n        -- NULL values are not part of the summaries and are not counted\n        IF asset_instance.proj_epsg IS NULL THEN\n            RETURN asset_instance;\n        END IF;\n\n        related_collection_id = (\n            SELECT collection_id FROM stac_api_item\n            WHERE id = asset_instance.item_id\n        );\n\n        -- Remove entry when count will reach 0\n        DELETE FROM stac_api_projepsgcount\n        WHERE collection_id = related_collection_id\n            AND value = asset_instance.proj_epsg\n            AND count = 1;\n\n        IF NOT FOUND THEN\n        UPDATE stac_api_projepsgcount\n        SET count = count-1\n        WHERE collection_id = related_collection_id\n            AND value = asset_instance.proj_epsg;\n\n        RAISE INFO\n            'projepsgcount (collection_id, value) (% %) count updated, due to asset.name=% update.',\n            related_collection_id, asset_instance.proj_epsg, asset_instance.name;\n\n        RETURN asset_instance;\n        END IF;\n\n        RAISE INFO\n            'projepsgcount (collection_id, value) (% %) deleted, due to asset.name=% update.',\n            related_collection_id, asset_instance.proj_epsg, asset_instance.name;\n\n        RETURN asset_instance;\n        ",
                    hash='3294f7e36b2725e3e166e20c0aa5276b9f3540ed',
                    operation='UPDATE',
                    pgid='pgtrigger_upd_dec_proj_epsg_trigger_17635',
                    table='stac_api_asset',
                    when='AFTER'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='asset',
            trigger=pgtrigger.compiler.Trigger(
                name='del_proj_epsg_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    declare=
                    'DECLARE asset_instance stac_api_asset%ROWTYPE; related_collection_id INT;',
                    func=
                    "\n        asset_instance = OLD;\n\n        -- NULL values are not part of the summaries and are not counted\n        IF asset_instance.proj_epsg IS NULL THEN\n            RETURN asset_instance;\n        END IF;\n\n        related_collection_id = (\n            SELECT collection_id FROM stac_api_item\n            WHERE id = asset_instance.item_id\n        );\n\n        -- Remove entry when count will reach 0\n        DELETE FROM stac_api_projepsgcount\n        WHERE collection_id = related_collection_id\n            AND value = asset_instance.proj_epsg\n            AND count = 1;\n\n        IF NOT FOUND THEN\n        UPDATE stac_api_projepsgcount\n        SET count = count-1\n        WHERE collection_id = related_collection_id\n            AND value = asset_instance.proj_epsg;\n\n        RAISE INFO\n            'projepsgcount (collection_id, value) (% %) count updated, due to asset.name=% update.',\n            related_collection_id, asset_instance.proj_epsg, asset_instance.name;\n\n        RETURN asset_instance;\n        END IF;\n\n        RAISE INFO\n            'projepsgcount (collection_id, value) (% %) deleted, due to asset.name=% update.',\n            related_collection_id, asset_instance.proj_epsg, asset_instance.name;\n\n        RETURN asset_instance;\n        ",
                    hash='3f8e2336ce5d3f63caa2ae8691c3469ecb1528df',
                    operation='DELETE',
                    pgid='pgtrigger_del_proj_epsg_trigger_c1652',
                    table='stac_api_asset',
                    when='AFTER'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='asset',
            trigger=pgtrigger.compiler.Trigger(
                name='upd_inc_proj_epsg_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD.proj_epsg IS DISTINCT FROM NEW.proj_epsg)',
                    declare=
                    'DECLARE asset_instance stac_api_asset%ROWTYPE; related_collection_id INT;',
                    func=
                    "\n        asset_instance = NEW;\n\n        -- NULL values are not part of the summaries and are not counted\n        IF asset_instance.proj_epsg IS NULL THEN\n            RETURN asset_instance;\n        END IF;\n\n        related_collection_id = (\n            SELECT collection_id FROM stac_api_item\n            WHERE id = asset_instance.item_id\n        );\n\n        INSERT INTO stac_api_projepsgcount (collection_id, value, count)\n        VALUES (related_collection_id, asset_instance.proj_epsg, 1)\n        ON CONFLICT (collection_id, value)\n        DO UPDATE SET count = stac_api_projepsgcount.count+1;\n\n        RAISE INFO\n            'projepsgcount (collection_id, value) (% %) count updated, due to asset.name=% update.',\n            related_collection_id, asset_instance.proj_epsg, asset_instance.name;\n\n        RETURN asset_instance;\n        ",
                    hash='e754d5e4a16afeeecd2cebc3a5f0daa78c1a5415',
                    operation='UPDATE',
                    pgid='pgtrigger_upd_inc_proj_epsg_trigger_ce669',
                    table='stac_api_asset',
                    when='AFTER'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='asset',
            trigger=pgtrigger.compiler.Trigger(
                name='add_proj_epsg_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    declare=
                    'DECLARE asset_instance stac_api_asset%ROWTYPE; related_collection_id INT;',
                    func=
                    "\n        asset_instance = NEW;\n\n        -- NULL values are not part of the summaries and are not counted\n        IF asset_instance.proj_epsg IS NULL THEN\n            RETURN asset_instance;\n        END IF;\n\n        related_collection_id = (\n            SELECT collection_id FROM stac_api_item\n            WHERE id = asset_instance.item_id\n        );\n\n        INSERT INTO stac_api_projepsgcount (collection_id, value, count)\n        VALUES (related_collection_id, asset_instance.proj_epsg, 1)\n        ON CONFLICT (collection_id, value)\n        DO UPDATE SET count = stac_api_projepsgcount.count+1;\n\n        RAISE INFO\n            'projepsgcount (collection_id, value) (% %) count updated, due to asset.name=% update.',\n            related_collection_id, asset_instance.proj_epsg, asset_instance.name;\n\n        RETURN asset_instance;\n        ",
                    hash='d1d4ec7a781a3cc17516566ba582164f13f32591',
                    operation='INSERT',
                    pgid='pgtrigger_add_proj_epsg_trigger_0dabc',
                    table='stac_api_asset',
                    when='AFTER'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='collectionasset',
            trigger=pgtrigger.compiler.Trigger(
                name='upd_dec_col_asset_proj_epsg_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."proj_epsg" IS DISTINCT FROM (NEW."proj_epsg"))',
                    declare=
                    'DECLARE asset_instance stac_api_collectionasset%ROWTYPE; related_collection_id INT;',
                    func=
                    "\n        asset_instance = OLD;\n\n        -- NULL values are not part of the summaries and are not counted\n        IF asset_instance.proj_epsg IS NULL THEN\n            RETURN asset_instance;\n        END IF;\n\n        related_collection_id = asset_instance.collection_id;\n\n        -- Remove entry when count will reach 0\n        DELETE FROM stac_api_projepsgcount\n        WHERE collection_id = related_collection_id\n            AND value = asset_instance.proj_epsg\n            AND count = 1;\n\n        IF NOT FOUND THEN\n        UPDATE stac_api_projepsgcount\n        SET count = count-1\n        WHERE collection_id = related_collection_id\n            AND value = asset_instance.proj_epsg;\n\n        RAISE INFO\n            'stac_api_projepsgcount (collection_id, value) (% %) count updated, due to asset.name=% update.',\n            related_collection_id, asset_instance.proj_epsg, asset_instance.name;\n\n        RETURN asset_instance;\n        END IF;\n\n        RAISE INFO\n            'stac_api_projepsgcount (collection_id, value) (% %) deleted, due to asset.name=% update.',\n            related_collection_id, asset_instance.proj_epsg, asset_instance.name;\n\n        RETURN asset_instance;\n        ",
                    hash='81a51ce970b82c59a80acbe065e1dd38710372ee',
                    operation='UPDATE',
                    pgid='pgtrigger_upd_dec_col_asset_proj_epsg_trigger_07a9d',
                    table='stac_api_collectionasset',
                    when='AFTER'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='collectionasset',
            trigger=pgtrigger.compiler.Trigger(
                name='del_col_asset_proj_epsg_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    declare=
                    'DECLARE asset_instance stac_api_collectionasset%ROWTYPE; related_collection_id INT;',
                    func=
                    "\n        asset_instance = OLD;\n\n        -- NULL values are not part of the summaries and are not counted\n        IF asset_instance.proj_epsg IS NULL THEN\n            RETURN asset_instance;\n        END IF;\n\n        related_collection_id = asset_instance.collection_id;\n\n        -- Remove entry when count will reach 0\n        DELETE FROM stac_api_projepsgcount\n        WHERE collection_id = related_collection_id\n            AND value = asset_instance.proj_epsg\n            AND count = 1;\n\n        IF NOT FOUND THEN\n        UPDATE stac_api_projepsgcount\n        SET count = count-1\n        WHERE collection_id = related_collection_id\n            AND value = asset_instance.proj_epsg;\n\n        RAISE INFO\n            'stac_api_projepsgcount (collection_id, value) (% %) count updated, due to asset.name=% update.',\n            related_collection_id, asset_instance.proj_epsg, asset_instance.name;\n\n        RETURN asset_instance;\n        END IF;\n\n        RAISE INFO\n            'stac_api_projepsgcount (collection_id, value) (% %) deleted, due to asset.name=% update.',\n            related_collection_id, asset_instance.proj_epsg, asset_instance.name;\n\n        RETURN asset_instance;\n        ",
                    hash='19b81098c89bf43842fd121eac2181c687700b1a',
                    operation='DELETE',
                    pgid='pgtrigger_del_col_asset_proj_epsg_trigger_2caf1',
                    table='stac_api_collectionasset',
                    when='AFTER'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='collectionasset',
            trigger=pgtrigger.compiler.Trigger(
                name='upd_inc_col_asset_proj_epsg_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."proj_epsg" IS DISTINCT FROM (NEW."proj_epsg"))',
                    declare=
                    'DECLARE asset_instance stac_api_collectionasset%ROWTYPE; related_collection_id INT;',
                    func=
                    "\n        asset_instance = NEW;\n\n        -- NULL values are not part of the summaries and are not counted\n        IF asset_instance.proj_epsg IS NULL THEN\n            RETURN asset_instance;\n        END IF;\n\n        related_collection_id = asset_instance.collection_id;\n\n        INSERT INTO stac_api_projepsgcount (collection_id, value, count)\n        VALUES (related_collection_id, asset_instance.proj_epsg, 1)\n        ON CONFLICT (collection_id, value)\n        DO UPDATE SET count = stac_api_projepsgcount.count+1;\n\n        RAISE INFO\n            'projepsgcount (collection_id, value) (% %) count updated, due to asset.name=% update.',\n            related_collection_id, asset_instance.proj_epsg, asset_instance.name;\n\n        RETURN asset_instance;\n        ",
                    hash='411f0943b07dd6745afde6e66d28c4bb07d5faad',
                    operation='UPDATE',
                    pgid='pgtrigger_upd_inc_col_asset_proj_epsg_trigger_d717d',
                    table='stac_api_collectionasset',
                    when='AFTER'
                )
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='collectionasset',
            trigger=pgtrigger.compiler.Trigger(
                name='add_col_asset_proj_epsg_trigger',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    declare=
                    'DECLARE asset_instance stac_api_collectionasset%ROWTYPE; related_collection_id INT;',
                    func=
                    "\n        asset_instance = NEW;\n\n        -- NULL values are not part of the summaries and are not counted\n        IF asset_instance.proj_epsg IS NULL THEN\n            RETURN asset_instance;\n        END IF;\n\n        related_collection_id = asset_instance.collection_id;\n\n        INSERT INTO stac_api_projepsgcount (collection_id, value, count)\n        VALUES (related_collection_id, asset_instance.proj_epsg, 1)\n        ON CONFLICT (collection_id, value)\n        DO UPDATE SET count = stac_api_projepsgcount.count+1;\n\n        RAISE INFO\n            'projepsgcount (collection_id, value) (% %) count updated, due to asset.name=% update.',\n            related_collection_id, asset_instance.proj_epsg, asset_instance.name;\n\n        RETURN asset_instance;\n        ",
                    hash='16053a4c1ae6cfd87b2fb482794befcf206187be',
                    operation='INSERT',
                    pgid='pgtrigger_add_col_asset_proj_epsg_trigger_e0d9a',
                    table='stac_api_collectionasset',
                    when='AFTER'
                )
            ),
        ),
    ]
